### ISSUE TITLE
User input out of range will not update input element

### ISSUE THREAD

**Issue by katsos** [dangrossman/daterangepicker#1237]
When user gives a date out of range and press enter and then "blur" out of the input,
the input value doesn't match the calendar's view.

<img width="613" alt="screen shot 2016-09-14 at 11 12 44 am" src="https://cloud.githubusercontent.com/assets/9785225/18504680/457a9b76-7a6c-11e6-8fdf-36d856cd9d66.png">

**Comment by olavocneto** [comment]
https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L418

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L1027

**Comment by smalltwo** [comment]
because it's isBefore the minDate, the setStartDate function has deal it
