### ISSUE TITLE
dropdowns - start year in right calendar is current year

### ISSUE THREAD

**Issue by DMITRYTISHKIN** [dangrossman/daterangepicker#1378]
![2017-05-09 14-27-10](https://cloud.githubusercontent.com/assets/20255399/25848774/796f7c86-34c4-11e7-89c3-2df3763e5386.png)
If selected year in left calendar, right calendar does not change start year

**Comment by DMITRYTISHKIN** [comment]
My fix this problem - #1371

**Comment by Nemecsek** [comment]
Not yet fixed after one year... Has it been forgotten?

**Comment by dangrossman** [comment]
It's not set to the current year, it's set to the year of the currently selected `startDate`

If you had clicked on something in May 2015 on the left, the right side dropdown would start at 2015 as well
