### ISSUE TITLE
Custom Range without linked calendars behaves surprisingly

### ISSUE THREAD

**Issue by Nucleotide** [dangrossman/daterangepicker#1434]
Hey,

I spotted this in my app with latest 2.1.25 and was also able to reproduce this with the demo at http://www.daterangepicker.com/

So simple config for the datepicker:
```javascript
$('#demo').daterangepicker({
    "showDropdowns": true,
    "linkedCalendars": false,
    "startDate": "03/17/2017",
    "endDate": "03/23/2017"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});
```

Now I do the following:
When I open the daterangepicker
And I choose the Custom Range
And I select year 2021 from the left calendar
And I select start date 03/10/2021
Then I see 03/10/2021 as the end date

![choose_start](https://cloud.githubusercontent.com/assets/352540/24264213/5f485f70-1008-11e7-9d77-0e218d566095.png)

When I hover over any date on the right calendar
Then the date on the right calendar jumps back to 2017
And the year dropdown shows wrong year (2017 vs 2021)

![proper_hov](https://cloud.githubusercontent.com/assets/352540/24264799/24c2c758-100a-11e7-9be5-428813480b95.png)

When I select a date from the right calendar it gets chosen as start date since it is before the start date I chose from the left calendar.

This does not happen when the calendars are linked with linkedCalendars. When calendars are linked, selecting start date and hovering on the right calendar works as expected.

Is this expected behaviour when calenders are not linked? I leads to confusing situations when all of a sudden the right calendar is used as the start date.

Cheers.

**Comment by Nucleotide** [comment]
Updated with proper screenie

**Comment by dangrossman** [comment]
Sounds like a bug to me

**Comment by justyy** [comment]
@Nucleotide I had repair the bug by commented code.
![image](https://user-images.githubusercontent.com/7438323/37591085-4ffdd414-2ba5-11e8-81c1-cbab41de8427.png)

**Comment by Nucleotide** [comment]
@justyy thx, we'll try that.
