### ISSUE TITLE
showDropdowns and linkedCalendars not working properly.

### ISSUE THREAD

**Issue by augustbend** [dangrossman/daterangepicker#1489]
This issue has been raised before, but I'm giving more details here:
The issue started since version 2.0.7 where the option linkedCalendars was added.
When you enable both (linkedCalendars and showDropDowns), and select a year from the first calendar (say 1999), the year combo in the other calendar displays no options to select.

![image](https://cloud.githubusercontent.com/assets/5343043/26558083/beb8c0f2-446b-11e7-8462-d905da8bf5e0.png)

**Comment by flashery** [comment]
I am also having this issue and I am using Bootstrap 4 Alpha

**Comment by ks1f14s** [comment]
It troubled me too. This is solved with:
parentEl: $('#modal_id')
as a parameter. The css inherits the modal_id and gets above. The default solution (inherits the body) was not working for me.
