### ISSUE TITLE
Time zone Sao Paulo - Brazil -- Oct month day 14th displayed twice

### ISSUE THREAD

**Issue by rksbala** [dangrossman/daterangepicker#1520]
Time zone: Sao Paulo - Brazil
Oct month day 14th displayed twice. Please check the jsfiddle example and navigate to Oct month. **This problem occurred in Safari & FF browser only.**

**Please change time zone in your system and try this.**
http://jsfiddle.net/csz9wm3q/

![image](https://user-images.githubusercontent.com/6780344/27760640-c8148462-5e22-11e7-8cb6-e7b540d8fd57.png)

This issue can reproducible http://www.daterangepicker.com/#examples
<img width="955" alt="daterange_picker" src="https://user-images.githubusercontent.com/6780344/27762616-2b105ef0-5e4c-11e7-9ebe-2d1b209f5e3d.png">

**Comment by PMeira** [comment]
The missing Oct 15 is when DST starts.  I'd imagine the issue could happen on other time zones besides the one reported here. I tested with moment.js 2.18.1 (latest), and later also found that there is an open issue about the inconsistent behavior across browsers: https://github.com/moment/moment/issues/2618

I checked in Firefox what was happening. For the 14th the date is `2017-10-14T03:00:00.000Z` (day=14 at the current TZ), but for the 15th it is `2017-10-15T02:00:00.000Z` which at the current timezone is day=14, hour=23.

Not sure what's the best way to handle this... For date pickers, one quick fix would be to add some hours (tested with 12) before extracting the date, i.e., change

`html += '<td class="' + cname.replace(/^\s+|\s+$/g, '') + '" data-title="' + 'r' + row + 'c' + col + '">' + calendar[row][col].date() + '</td>';`

to

`html += '<td class="' + cname.replace(/^\s+|\s+$/g, '') + '" data-title="' + 'r' + row + 'c' + col + '">' + calendar[row][col].add(12, 'hour').date() + '</td>';`

**Comment by rksbala** [comment]
Thank you for your suggestion.
Added time zone based work around. For brazil time zone alone added utc()

calendar[row][col] = curDate.clone().hour(hour).minute(minute).second(second);
curDate.hour(12);

to

calendar[row][col] = curDate.clone().hour(hour).minute(minute).second(second).utc();
