### ISSUE TITLE
Year is not switched when showDropdowns option is enabled

### ISSUE THREAD

**Issue by rommeras** [dangrossman/daterangepicker#1521]
$('#demo').daterangepicker({
    "showDropdowns": true,
    "startDate": "06/28/2017",
    "endDate": "07/04/2017"
}, function(start, end, label) {
  console.log("New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')");
});

When "showDropdowns" is set "true", open calendar, click left arrow until you see Dec 2016 - January 2017 on left and right calendar accordingly. Click left arrow one more time. Year on right calendar is not updated in dropdown, it still shows 2017.

Please fix

**Comment by dangrossman** [comment]
Yes, there are some bugs with showDropdowns

Please fix and submit a PR

I don't have time to work on this library in the immediate future

**Comment by gangstead** [comment]
I think there already exists an open PR which fixes this: #1460

**Comment by StabbarN** [comment]
That PR doesn't fix this. We are also experiencing this issue.

Tested on both Chrome and Firefox. To reproduce:
1) Open http://www.daterangepicker.com/#config
2) Enable "showDropdowns" and set minYear to 2015.
3) Use the dropdown in the left calendar to switch year to 2017.
4) Notice that the right pane isn't updated. It's still showing year 2018 in the dropdown. See screenshot below 
<img width="1032" alt="dropdown minyear" src="https://user-images.githubusercontent.com/921390/48347590-f249f100-e67e-11e8-8d43-e46320188fc1.png">
