### ISSUE TITLE
keyboard input with hidden dialog bug

### ISSUE THREAD

**Issue by romannep** [dangrossman/daterangepicker#1631]
1. Focus input - dialog opens
2. Input date by keyboard, press Enter - everything ok. Focus remained on the element, dialog hides.
3. Input new date by keyboard - no callback function no apply.daterangepicker event fired, but date changes.

Simple solution: remove 
````
if (!this.isShowing) return;
````
in `hide` method.

**Comment by diegolido** [comment]
I guess this could fiz your problem.
https://github.com/dangrossman/bootstrap-daterangepicker/pull/1661
