### ISSUE TITLE
Bug on iOS devices when click outside input

### ISSUE THREAD

**Issue by bagendahl** [dangrossman/daterangepicker#1663]
Quick explanation:
1. autoApply: true
2. Click input of daterangepicker, calendar opens
3. Click somewhere outside input or calendar to scroll on page
4. Calendar will then close automatically
5. Try to click input again to open and nothing happens

Issue: 
It seems that on iOS (haven't tried other devices) doesn't unbind field which result to not trigger open calendar again.

Summary:
It works fine on desktop. I also tried on my Ipad and iPhone on page http://www.daterangepicker.com/ and get the same result. Haven't tried other browser only safari. 

Does any body else got the same issue/bug?

**Comment by kgrigorian** [comment]
Also have this issue on iphone

**Comment by wilywork** [comment]
+1, if I find a solution,i put here

**Comment by wilywork** [comment]
work in ios
`        //
        // event listeners
        //

        var userAgent = navigator.userAgent.toLowerCase();
        var deviceIOS = false;

        if( userAgent.search(/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i)!= -1 ){
            if( userAgent.search(/(android|avantgo|blackberry|bolt|boost|cricket|docomo)/i) == -1 ){
                deviceIOS = true;
            }
        }

        this.container.find('.calendar')
            .on('click.daterangepicker', '.prev', $.proxy(this.clickPrev, this))
            .on('click.daterangepicker', '.next', $.proxy(this.clickNext, this))

            .on(deviceIOS ? 'touchend.daterangepicker' : 'mousedown.daterangepicker', 'td.available', $.proxy(this.clickDate, this))
            .on(deviceIOS ? 'touchstart.daterangepicker' : 'mouseenter.daterangepicker', 'td.available', $.proxy(this.hoverDate, this))
            .on(deviceIOS ? 'touchleave.daterangepicker' : 'mouseleave.daterangepicker', 'td.available', $.proxy(this.updateFormInputs, this))

            .on('change.daterangepicker', 'select.yearselect', $.proxy(this.monthOrYearChanged, this))
            .on('change.daterangepicker', 'select.monthselect', $.proxy(this.monthOrYearChanged, this))
            .on('change.daterangepicker', 'select.hourselect,select.minuteselect,select.secondselect,select.ampmselect', $.proxy(this.timeChanged, this))
            .on('click.daterangepicker', '.daterangepicker_input input', $.proxy(this.showCalendars, this))
            .on('focus.daterangepicker', '.daterangepicker_input input', $.proxy(this.formInputsFocused, this))
            .on('blur.daterangepicker', '.daterangepicker_input input', $.proxy(this.formInputsBlurred, this))
            .on('change.daterangepicker', '.daterangepicker_input input', $.proxy(this.formInputsChanged, this))
            .on('keydown.daterangepicker', '.daterangepicker_input input', $.proxy(this.formInputsKeydown, this));`

**Comment by kgrigorian** [comment]
where do u add it? in daterangepicker.js

**Comment by wilywork** [comment]
yes, replace //event listeners, the plugin.

daterangepicker 2.1.30 edited .min

[daterangepicker.min.zip](https://github.com/dangrossman/bootstrap-daterangepicker/files/1723474/daterangepicker.min.zip)

**Comment by kgrigorian** [comment]
Didnt work for me. If click somewhere outside of CP it closes and wont open again until 'Done' is clicked in right down corner of safari
