### ISSUE TITLE
Can't select 15 Apr 1982 with showDropdowns=true

### ISSUE THREAD

**Issue by peyote** [dangrossman/daterangepicker#1664]
Can't select 15 Apr 1982 with showDropdowns=true

Date jumps from April to March

**Comment by peyote** [comment]
In Ubuntu Firefox Quantum 57.0.4 (64-bit):
moment([1982, 3]).daysInMonth() returns 31
moment([2018, 3]).daysInMonth() returns 30

**Comment by dangrossman** [comment]
I'm able to select 15 Apr 1982 with showDropdowns=true

Those both return 30 in Firefox on Windows

**Comment by peyote** [comment]
Weird. See attached.

![bug-ubuntu-ff-quantum-apr-1982](https://user-images.githubusercontent.com/1240879/35430332-7baa1fe4-0280-11e8-9bb2-b6d1be5bb682.png)
