### ISSUE TITLE
Add support for Font Awesome 5

### ISSUE THREAD

**Issue by bryandh** [dangrossman/daterangepicker#1675]
Currently, the daterangepicker will display like it does in the following images:

Using **Font Awesome 5 Web Fonts with CSS**
`<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">`
<img width="659" alt="screenshot 2018-02-21 16 15 13" src="https://user-images.githubusercontent.com/11500592/36487934-6df67bde-1722-11e8-99f5-225e75c85ac7.png">

Using **Font Awesome 5 SVG with JS**
`<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>`
<img width="661" alt="screenshot 2018-02-21 15 34 43" src="https://user-images.githubusercontent.com/11500592/36485764-2bd54adc-171d-11e8-8e77-ff8cff9cceb0.png">

As you can see the icons of the date input and left to the time inputs are missing/broken/misplaced.

**Comment by bryandh** [comment]
I've come up with a workaround to replace the icons with FontAwesome 5 icons:

```
// HOTFIX: replaced bootstrap-daterangepicker's clock icons with Font Awesome 5 clock icons
const existingClockIcons = document
    .getElementsByClassName('daterangepicker')
    .item(0)
    .getElementsByClassName('fa-clock-o');
const newClockIcon = document.createElement('i');
newClockIcon.classList.add('far', 'fa-clock');
existingClockIcons.item(0).parentNode.replaceChild(newClockIcon, existingClockIcons.item(0));
existingClockIcons.item(0).parentNode.replaceChild(newClockIcon.cloneNode(), existingClockIcons.item(0));

**Comment by Zhakrin** [comment]
You can also edit the template itself by adding the template option when you create the daterangepicker:
