### ISSUE TITLE
General issues with Picker and bound Input keeping in sync.

### ISSUE THREAD

**Issue by weisborg** [dangrossman/daterangepicker#1681]
```
autoUpdateInput: false,
singleDatePicker: true,
timePicker: true,
timePickerIncrement: 1,
timePicker24Hour: true,
locale: {
	format: 'MM/DD/YYYY HH:mm',
	cancelLabel: 'Clear'
}
```
Time Dropdowns seem to just keep their own values and not stay in sync with input.  Like, If they get changed then the user clicks off of the picker which cancels the changes. When opened again the time dropdowns have the last picked values instead of the values in the inputs.  It doesn't seem to keep them in sync on init of the picker too if a value is in the input it reads the date, but the time dropdowns will show 0:00.  Really annoys the users since they will click to change just the date and their time then gets reset to 0:00.

**Comment by jstnryan** [comment]
After struggling with the same issue for quite some time, I solved it by forcing an update every time the picker is shown, for example:

    $('#daterange').on('show.daterangepicker', function(event, picker) {
        $('#daterange').data('daterangepicker').setStartDate($(this).val());
        picker.updateView();
    });

`updateView` isn't documented; [I found it here](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js#L536).

**Comment by weisborg** [comment]
Didn't get notified of this for some reason.  Thanks for the tip.  I've also found if I trigger a keyup event on the input when I update the date from JavaScript forces the picker to sync.  I'm sure if this was fixed internally to update the picker as it does for keyup every time the picker is shown it would be a much better/cleaner fix than handling or triggering events ourselves.
