### ISSUE TITLE
Tabbing navigation issue

### ISSUE THREAD

**Issue by JaewoongShin** [dangrossman/daterangepicker#1682]
Hi,

I am testing the drop down list including 'Past 7 days', 'Past 30 days', 'This year', 'Custom Apply' of the calendar.
It looks like it is not able to tab through all the elements of the drop down menu, which means it does not comply with WCAG. (See the link below)

https://www.w3.org/TR/REC-html40/interact/forms.html#adef-tabindex

Can you guys tell me any ways to resolve this?

**Comment by OlivierGrimard** [comment]
+1
