### ISSUE TITLE
alwaysShowCalendars :)

### ISSUE THREAD

**Issue by grekpg** [dangrossman/daterangepicker#1684]
im looking to way to disable on open calendars, this option alwaysShowCalendars - is like sometimesShowCalendar in my app - i set alwaysShowCalendars : false 
open daterangepicker - it have calendar and ranges, - if select range close then open - now i don't see calendars. 
Is possible to set - dontShowCalendarsIfNotSelectedCustom = default calendars is hidden and if user select custom range - and reopen then see calendars ?

**Comment by dangrossman** [comment]
The calendars are visible if the current `startDate` and `endDate` do not exactly match any of your predefined ranges
