### ISSUE TITLE
Can I show Only one button out of Apply and Cancel as per my need?

### ISSUE THREAD

**Issue by akashqwerty** [dangrossman/daterangepicker#1685]
Can I show Only one button out of Apply and Cancel as per my need? Currently I am using either autoApply and it shows either both or none. Also Is there any option that buttons only show up when custom date range is enabled? Or I have to do it myself using jqury+css?

**Comment by dangrossman** [comment]
Both buttons are enabled or disabled by the same settings, so you would need to use CSS to hide only one
