### ISSUE TITLE
Font awesome 5

### ISSUE THREAD

**Issue by LeorentKelmendi** [dangrossman/daterangepicker#1692]
Just updated my font awesome to `fas` and the whole datarange picker its out of order:
![image](https://user-images.githubusercontent.com/23528898/37330908-c80bb14a-26a2-11e8-9160-bd3b8f15b03f.png)

 any support for fa5 ?

**Comment by uok** [comment]
In Font Awesome 5 the icons have a [new syntax](https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes)

`fa fa-calendar` -> `far fa-calendar-alt`
`fa fa-chevron-left` -> `fas fa-chevron-left`
`fa fa-chevron-right` -> `fas fa-chevron-right`
`fa fa-clock-o` -> `far fa-clock`
