### ISSUE TITLE
Selecting end date after click in input and then change month

### ISSUE THREAD

**Issue by andremiguelaa** [dangrossman/daterangepicker#1699]
Steps to reproduce:

1. Click on calendar to select start date
2. Click on end date input text
3. Change to next month
4. Select a date in calendar

What I expect: Change the end date (and that's what's happening if you don't change the month)
What really happens: Change the start date

![6](https://user-images.githubusercontent.com/1964691/37707944-c9ffb5b8-2cfc-11e8-8cac-2736b2820ba4.gif)

**Comment by siemiatj** [comment]
Yeah, it's really annoying that focus is automatically switched to the startDate input. I think what could help as well would be an option to turn off picking date when day is hovered. Right now for a short moment user sees the same end and start dates.

![kr6dwshuda](https://user-images.githubusercontent.com/513460/37718077-2a1da6e2-2d22-11e8-825f-6833c3118f36.gif)

@andremiguelaa try if setting `linkedCalendars: false` doesn't help a bit. I found the experience to be much better now.

**Comment by andremiguelaa** [comment]
The experience is better with `linkedCalendars: false`, no doubt about it, but the problem persists.

**Comment by dangrossman** [comment]
Two different "problems"

When you click on the text input, then click out of the text input, your text entry is saved as the new end date selection

If you've just selected a start date and an end date, your next click is selection of a new date range (start date) not changing the end date

There is no way for the code to know that you changed your mind about using the text input for some reason

**Comment by andremiguelaa** [comment]
But if we don't change the month we can set an end date after click in the input. That's an incoherent behaviour.

Steps to reproduce:

1. Click on calendar to select start date
2. Click on end date input text
3. DON'T Change to next month
4. Select a date in calendar

**Comment by andremiguelaa** [comment]
Do you have any idea to solve the problem?

**Comment by dangrossman** [comment]
By removing the inputs from the UI, which is what I've done

They have been more confusing than useful
