### ISSUE TITLE
Rounds date to next day

### ISSUE THREAD

**Issue by fruitbatinshades** [dangrossman/daterangepicker#1705]
I am sending a date range of :
Start: 2018-03-01T00:00:00.000Z
End: 2018-03-31T23:59:59.000Z

The control rounds the end date up and displays:

01/03/2018 - 01/04/2018

Is there any way to stop the date rounding up?

**Comment by dangrossman** [comment]
Try sending the string "2018-03-31" or whatever your date format string is?
