### ISSUE TITLE
Change date formats based on locale

### ISSUE THREAD

**Issue by VudugulaRamu** [dangrossman/daterangepicker#1716]
Hi @dangrossman,

I just want to display date format based on a locale 
eg. for USA locale: en-US, format: MM/DD/YYYY

In date range picker we have a property like "locale: {format: 'YYYY/MM/DD'}". How can i change format of a date without specifying the format in locale

**Comment by dangrossman** [comment]
The default format is pulled from `moment.localeData().longDateFormat('L')`, so if you set a different locale globally in the moment object on your page, that would affect your date pickers as well
