### ISSUE TITLE
When I set the timepickerIncrement to some value, the calendar does not close.

### ISSUE THREAD

**Issue by iamankit1995** [dangrossman/daterangepicker#1721]
`<DateRangePicker
              id="datetimerangepicker"
              startDate={moment(this.state.startDate, moment.ISO_8601)}
              endDate={moment(this.state.endDate, moment.ISO_8601)}
              onApply={this.handleDateRange}
              minDate={moment(this.state.minDate, moment.ISO_8601)}
              maxDate={moment(this.state.curDate, moment.ISO_8601)}
              timePicker={true}
              timePicker24Hour={true}
              timePickerIncrement={60}
              ranges={{
                '1D': [moment(this.state.curDate, moment.ISO_8601).subtract(1, 'days'), moment(this.state.curDate, moment.ISO_8601)],
                '2D': [moment(this.state.curDate, moment.ISO_8601).subtract(2, 'days'), moment(this.state.curDate, moment.ISO_8601)],
                '7D': [moment(this.state.curDate, moment.ISO_8601).subtract(7, 'days'), moment(this.state.curDate, moment.ISO_8601)],
                '30D': [moment(this.state.curDate, moment.ISO_8601).subtract(30, 'days'), moment(this.state.curDate, moment.ISO_8601)],
              }}
              showCustomRangeLabel={true}
              >`
The calendar does not disappear on clicking predefined ranges

**Comment by dangrossman** [comment]
Perhaps hide the minute picker with CSS instead
