### ISSUE TITLE
How can i import bootstrap-daterangepicker as es6 module

### ISSUE THREAD

**Issue by guitar9** [dangrossman/daterangepicker#1723]
hi installed bootstrap-daterangepicker with
npm i daterangepicker
and want  to import  it with
import daterangepicker from "daterangepicker"

but it does not work

**Comment by hlawuleka** [comment]
May you provide the "Not working" code. Because a mere: `import 'path/to/the-date-range-picker'` should do the job.

**Comment by dangrossman** [comment]
I don't know anything about ES6 modules, so I would ask on StackOverflow if you still have this problem
