### ISSUE TITLE
Option to disable today's date by default in the field?

### ISSUE THREAD

**Issue by Cipa** [dangrossman/daterangepicker#1734]
Hi,

I am having a hard time figuring out why the date field is populated with the current date when the value of the input is empty.

Is there an option to disable the value? 

I use:
```
$('#editByDate, #reviewByDate, #additionalReviewByDate ').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
    });
```

These date fields are not all mandatory so they should be empty by default.

Thank you

**Comment by Cipa** [comment]
This seems to work(), but an option to do this by default would be nice

$('#editByDate, #reviewByDate, #additionalReviewByDate').daterangepicker({
        autoUpdateInput: false, //disable default date
        singleDatePicker: true,
        showDropdowns: true,
    });
    //we need to populate with selected date because we had disable autoUpdateInput above
    $('#editByDate, #reviewByDate, #additionalReviewByDate').on('apply.daterangepicker', function (ev, picker) {
        $(this).val(picker.startDate.format('MM/DD/YYYY'));
    });

Pls close this or maybe add it as an improvement request. I will close in a few day if no answer

Thank you

**Comment by dangrossman** [comment]
You've got it right, that's the 5th example on the documentation site

http://www.daterangepicker.com/#example5

Internally there is always a date selected, null/nothing is not supported right now
