### ISSUE TITLE
Error "Cannot read property 'contains' of undefined" is thrown in a page without any calendar

### ISSUE THREAD

**Issue by MiguelAngel82** [dangrossman/daterangepicker#1735]
Hello all.

I'm using the  daterangepicker (last version) in a Grails application. This library has been added to a main JS file, named as `application.js`. This file is used by Asset Pipeline plugin and requires jQuery and moment before using daterangepicker. This file is also loaded in the bottom of the page.

When the main view of the app is loaded, this error is thrown, when you clicked in some page area:

```
jquery.daterangepicker.js?compile=false:5565 Uncaught TypeError: Cannot read property 'contains' of undefined
    at IsOwnDatePickerClicked (jquery.daterangepicker.js?compile=false:5565)
    at HTMLDocument.outsideClickClose (jquery.daterangepicker.js?compile=false:7113)
    at HTMLDocument.dispatch (jquery-2.2.0.min.js?compile=false:3)
    at HTMLDocument.r.handle (jquery-2.2.0.min.js?compile=false:3)
```
Maybe is a problem in load order or something similar.

Any help is appreciate :)

Thank you.

Regards,
Miguel.﻿

​

**Comment by dangrossman** [comment]
You are not using this date range picker library. You appear to be using this one based on those function names: https://github.com/longbill/jquery-date-range-picker

**Comment by MiguelAngel82** [comment]
Ops, sorry, you are right. It's my fault.
