### ISSUE TITLE
daterangepicker - the calendar's position is swapped ?

### ISSUE THREAD

**Issue by leguminosa** [dangrossman/daterangepicker#1743]
i see when i'm using your daterangepicker js (ver 2.1.18) but retain the css by another daterangepicker project (i guess it's bootsrap's - yeah the css daterangepicker-bs3.css) the position is swapped
I know by using your own daterangepicker.css everything is clear, nice and neat, but...could you possibly tell me where exactly the code to put those position (maybe i can tweak it myself so that i can swap the position myself, maybe)

![aaaa](https://user-images.githubusercontent.com/38403278/39961615-5297cb00-5664-11e8-8f1b-7c9bede5d340.PNG)

Thanks for your help. appreciate your good work.

**Comment by dangrossman** [comment]
Why wouldn't you use the CSS file that came with that version of the JavaScript file? Regardless, I don't recall there being any code that swaps the two calendars. You're probably just missing some floats or something that would've put them in order.

https://github.com/dangrossman/daterangepicker/blob/v2.1.18/daterangepicker.css

**Comment by dangrossman** [comment]
Current version is 3.0.2

https://github.com/dangrossman/daterangepicker/releases

**Comment by leguminosa** [comment]
thanks dude, I'll download it...
oh btw, do your daterangepicker have a feature to disable some day in a week ?
