### ISSUE TITLE
set default time 

### ISSUE THREAD

**Issue by sewox** [dangrossman/daterangepicker#1746]
I want to set the time as 00:00:00 and 23:59:59

**Comment by dangrossman** [comment]
I'm not sure what a "default time" would be? For the time picker? It uses the time component of your `startDate` and `endDate`. If it's for anything else, you can set the time component of a date object to whatever you want before you save it, use it, whatever you're doing with it. http://momentjs.com/docs/#/get-set/

**Comment by sewox** [comment]
I want the start time to be 00:00:00 and the end time to be 23:59:59 until the user changes it
