### ISSUE TITLE
How to add financial year in period section

### ISSUE THREAD

**Issue by naveensaravanan** [dangrossman/daterangepicker#1750]
In period section have lot of options (Days, Weeks, Month, Quarter, Year). How to add **financial year** in this calendar.

**Comment by dangrossman** [comment]
http://www.daterangepicker.com/#example4
http://momentjs.com/docs/

**Comment by naveensaravanan** [comment]
I want  like this. 
![img3](https://user-images.githubusercontent.com/15015972/40216182-b35baa2a-5a82-11e8-8716-8b1a643a3a8e.png)

**Comment by dangrossman** [comment]
I think you're at the wrong project

**Comment by naveensaravanan** [comment]
Maybe I choose wrong plugin. anyway thanks @dangrossman
