### ISSUE TITLE
Right-to-left click order

### ISSUE THREAD

**Issue by vanderlee** [dangrossman/daterangepicker#1755]
When picking a range on the calendar, if you select a date on the calendar before the end-date of the currently selected range, the entire range is deselected.

This behaviour makes it hard to select a range from several years in the past up to very recently when using connected calendars. You first have to click several years into the past, click the start-date, then click all the way up to the current year again to select the end-date.

Is there any way to change this default behaviour as to make each click select one (altering) end-point of the selected range or something similar?

**Comment by vanderlee** [comment]
I understand this bug is not going to be fixed?

**Comment by dangrossman** [comment]
What you described isn't a bug.
