### ISSUE TITLE
Datelimit is counting disabled weekends

### ISSUE THREAD

**Issue by OctavioCH** [dangrossman/daterangepicker#1763]
Hi I am using daterangepicker and already disabled weekends with IsInvalidDate function, but when using DATELIMIT is counting weekend, for example a have a 3 days datelimit and I want to select FRIDAY, MONDAY and TUESDAY, but when I click in FRIDAY it wont let select MONDAY because it is counting saturday and sunday as 2 and 3.

Could anyone please advice? Or if somebody knows how to hide weekends (not sure if it would still count weekends or not).

**Comment by dangrossman** [comment]
Your custom requirement of a maximum range excluding weekends is something you need to program yourself. Hiding the weekends would not change how the `dateLimit` setting works.
