### ISSUE TITLE
No past dates allowed.

### ISSUE THREAD

**Issue by emresaracoglu** [dangrossman/daterangepicker#1769]
Hello,

How do I block the selection of history for date-range? I want to be elected today and future dates, not history dates.
Can you help me?

Thank you

**Comment by dangrossman** [comment]
http://www.daterangepicker.com/#options

````$('#element').daterangepicker({ 
 minDate: moment()
});
````

**Comment by emresaracoglu** [comment]
Thank you @dangrossman
