### ISSUE TITLE
DRPTemplate appendTo parent is not working correctly

### ISSUE THREAD

**Issue by rakia** [dangrossman/daterangepicker#1770]
Hello,

I'm using daterangepicker V 1.3.23, and it seems like the DRPTemplate is not always correctly appended to the parentEl. That happens on mobile browser, sometimes the daterangepicker is not opened and not displayed after a click on it, and the DOM of DRPTemplate is not found in the view HTML.

Any help will be appreciated!
Thanks

**Comment by dangrossman** [comment]
This library is currently version 3.0.3. V1 came out 6 years ago. Please upgrade before asking for help.
