### ISSUE TITLE
Setting language

### ISSUE THREAD

**Issue by handecavsi** [dangrossman/daterangepicker#1777]
Hello,
I can change date format with locale function but how can I change language of daterangepicker?

**Comment by Dee-Fuse** [comment]
You can specify anything with the `locale` settings
```JS
  "locale": {
        "format": "MM/DD/YYYY",
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Cancel",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "Su",
            "Mo",
            "Tu",
            "We",
            "Th",
            "Fr",
            "Sa"
        ],
        "monthNames": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        "firstDay": 1
    },
```

**Comment by thpsjsys** [comment]
how to do change language to en? Cause default is in Russian. I tried but cannot work. Please give an example

**Comment by handecavsi** [comment]
Thank you. I tried and it works.

**Comment by thpsjsys** [comment]
I tried this:
            locale: {
                applyLabel: 'Apply',
                cancelLabel: 'Cancel',
                startLabel: 'Start date',
                endLabel: 'End date',
                customRangeLabel: 'Custom Range',
                daysOfWeek: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            }
but still in russian

**Comment by dangrossman** [comment]
What is in Russian? There's no Russian text in this library.

**Comment by handecavsi** [comment]
Hello,
How can I block past dates and weekend days at date range picker? I can
block weekend days or I can block past dates but I can't do both of them.


 for past dates:


  var today = new Date();
            var dd = today.getDate();
            var mm = today.getMonth()+1; //January is 0!
            var yyyy = today.getFullYear();
            if(dd<10){ dd='0'+dd }
            if(mm<10){ mm='0'+mm }
            var today = dd+'/'+mm+'/'+yyyy;

$('#'+'izin_baslangic'+atablo_satir_sayisi).daterangepicker({
                        minDate:today
                });



for weekend days

 $('#'+'izin_baslangic'+atablo_satir_sayisi).daterangepicker({
                   isInvalidDate: function(date) {
                     return (date.day() == 0 || date.day() == 6);
                   }
                });


How can I use  functions both of them?.

2018-06-19 15:17 GMT+03:00 DeeFuse <notifications@github.com>:

**Comment by dangrossman** [comment]
Like so:

````
 $('#'+'izin_baslangic'+atablo_satir_sayisi).daterangepicker({
                   isInvalidDate: function(date) {
                     return (date.day() == 0 || date.day() == 6);
                   },
                   minDate: moment()
                });
````

**Comment by handecavsi** [comment]
Thanks. It works

**Comment by dmytro-shchurov** [comment]
What about using of global moment locale settings? For example it could be enough just to call `moment.locale('es')` before the _daterangepicker_ is rendered. Is this possible?

**Comment by 7dir** [comment]
needs adding to example: someone do this
