### ISSUE TITLE
Predefined Ranges  -  Always highlighted today 

### ISSUE THREAD

**Issue by pptyasar** [dangrossman/daterangepicker#1779]
When refreshing page and giving value for start date and end  date predefined ranges are not correctly highlighted. Always today is highlighted.

**Comment by dangrossman** [comment]
Can you share the webpage, jsfiddle, or code that has this problem?

**Comment by pptyasar** [comment]
Got solution. Should give 
`            startDate: startDt, endDate: endDt,`
value in initializing daterangepicker
