### ISSUE TITLE
Modern day.js support

### ISSUE THREAD

**Issue by Aleg-1990** [dangrossman/daterangepicker#1780]
Is there a way to replace moment.js with modern lightweight day.js library? Or maybe it will be better to add compatibility of day.js library and make both dayjs and momentjs optional dependencies? Thank you.
https://github.com/iamkun/dayjs

**Comment by dangrossman** [comment]
That's a good question you may want to explore since you're interested. I do not have the time.

**Comment by Ciki** [comment]
@Aleg-1990 by any chance have you looked into this?
