### ISSUE TITLE
Disable the listing of days of the next month with the previous month when double is enabled

### ISSUE THREAD

**Issue by ehausen** [dangrossman/daterangepicker#1781]
I'm required to not have to achieve something like this:
![screen shot 2018-06-21 at 12 18 50](https://user-images.githubusercontent.com/6204129/41710052-5d6d19ce-754d-11e8-9cbb-1f93d04a25b7.png)

So when double calendar is enabled we would need to disable listing of the next month's days with the previous month.

Especially if the first day of the week is the first day of the month, it currently looks weird:
![screen shot 2018-06-21 at 12 23 39](https://user-images.githubusercontent.com/6204129/41710368-27e70066-754e-11e8-8c16-73d22d9a21b2.png)

This functionality of course has it's place when we only have one month at the time, but with two month selector it is not the best.

Can I disable it quite easily somehow? I did not find a setting.
Where is this handled in the code?

**Comment by ehausen** [comment]
I can achieve something like that by messing with css, but it does not quite work..

**Comment by dangrossman** [comment]
If CSS doesn't quite work for you, here's where to start adding your custom code:

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L777
