### ISSUE TITLE
Clear the range selected after Cancel

### ISSUE THREAD

**Issue by w-mazed** [dangrossman/daterangepicker#1788]
Hi,

Is there a method to clear the selected range with a method, we can need that after apply or cancel the pop-up calendar, thx;

Best regards.

**Comment by dangrossman** [comment]
There is always a selected range in this library. By default it's today's date to today's date if you don't specify your own `startDate` and `endDate`.

**Comment by adamgp** [comment]
Hi Dan,

How feasible would it be to support no date and the ability to cancel/clear the current selection.

Thanks

**Comment by w-mazed** [comment]
@dangrossman what I'm tryin' to explain is: if we select a range of date (start - end) and after that we cancel the calendar and open it twice we'll find the previous range, so how can I avoid that please.

**Comment by w-mazed** [comment]
@dangrossman Okay that's fine, thank you for all your answers :)

**Comment by theNotoriousHxc** [comment]
@dangrossman wouldn't it be possible as a feature request to add the usual reset functionality of deselecting the previously selected date/date-range?

**Comment by dangrossman** [comment]
1- There's nobody here taking feature requests

2- It would not be an easy feature to implement in this code

**Comment by wesforsyth** [comment]
Hi guys, found a way around this :)
