### ISSUE TITLE
Custom label in date range picker instead of date format 

### ISSUE THREAD

**Issue by zinnira** [dangrossman/daterangepicker#1795]
I want to update my input field with a custom label reading "Start Date" instead of showing date format. How can I change that 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/31683743/42570855-b0854ff0-852e-11e8-85ac-d544b0cff65a.png">

**Comment by dangrossman** [comment]
Either use `autoUpdateInput: false` in your picker options, or attach the picker to an element that isn't a text input, since you apparently just want to show some text on your webpage anyway. Like `<div id="picker">Start Date<i class="fa fa-calendar"></i></div>`.
