### ISSUE TITLE
clear date with singleDatePicker

### ISSUE THREAD

**Issue by cc616** [dangrossman/daterangepicker#1796]
I am using singleDatePicker, and I have a clear icon, when I click clear icon, I call 'setStartDate' function like this:
```
$('.js-start-date').data('daterangepicker').setStartDate('');
```
then, when I again select date, the style like this
![image](https://user-images.githubusercontent.com/9332135/42675931-a0a06cb6-86a8-11e8-94b9-a20de202abf1.png)
it still has some background color
how can I fixed this problem

**Comment by dangrossman** [comment]
This library does not support having no date selected internally. You cannot call `setStartDate('')`, you must provide a date.

**Comment by cc616** [comment]
how can I clear date?
