### ISSUE TITLE
Can i use this in angular 6 ? 

### ISSUE THREAD

**Issue by Phetz** [dangrossman/daterangepicker#1800]
i'm start learning  angular  and i need to make calendar show two month at once , my question is , can i use this calendar in my app ?,if not , can you suggest another calendar  look like this ?

thank you

**Comment by dangrossman** [comment]
I don't know anything about angular. This is a javascript library that uses jquery. It can be used in a webpage.

**Comment by crjacinro** [comment]
@dangrossman, it would be better to support angular. This library is cool and plain JS -> jquery is becoming obsolete.

**Comment by ahmadmu** [comment]
As of Angular 8: You need to install `moment`, `jquery`, `daterangepicker`, and `@types/daterangepicker` first, import them into your component and then write something similar to this:

```
<div #calender>
  <input type="text">
</div>

```
```
import * as $ from 'jquery';
import * as moment from 'moment';
import * as daterangepicker from 'daterangepicker';

...

@ViewChild('calender', {static: true}) calender: ElementRef;

ngOnInit() {
    const dp = new daterangepicker(this.calender.nativeElement ,{
      // options
    }, function (start, end, label) {
      console.log(start, end, label)
    });
  }
```

**Comment by rajkhan91** [comment]
@ahmadmu i have implemented the same code what you have suggested above calendar working fine but the problem is that :
the value of start, end and label are not reflected out side of this function. 

--->> }, function (start, end, label) {
      console.log(start, end, label)
});

**Comment by VamshiRajarikam** [comment]
@rajkhan91 
You can use the below example

`import * as $ from 'jquery';
import * as moment from 'moment';
import * as daterangepicker from 'daterangepicker';

...

@ViewChild('calender', {static: true}) calender: ElementRef;
public calendarDate;

ngOnInit() {
    this.calendarDate = new daterangepicker(this.calender.nativeElement ,{
   timePicker: true,
        startDate: moment().startOf('hour'),
        endDate: moment()
          .startOf('hour')
          .add(32, 'hour'),
        locale: {
          format: 'MM/DD/YYYY hh:mm A',
        },
    }, function (start, end, label) {
      console.log(start, end, label)
    });
  }

changeStartAndEndDate(){
    this.calendarDate.setStartDate('03/01/2014');
    this.calendarDate.setEndDate('06/01/2014');
}
`
Refer: http://www.daterangepicker.com/#methods
