### ISSUE TITLE
FR: Dont jump to first date

### ISSUE THREAD

**Issue by achtan** [dangrossman/daterangepicker#1801]
Dont jump to first date when multiple months are selected
example:
http://www.giphy.com/gifs/pObL1CdU4u2iNitpfQ

pls add option to disable auto-jumping to the first date of selected range...

**Comment by dangrossman** [comment]
Take a look at the `linkedCalendars` option.

**Comment by achtan** [comment]
hi, `linkedCalendars` is not exactly what i am looking for...
i need following behaviour:
lets assume i have selected range 5.5.2017 - 6.6.2018
- when i open calendar i want to see last two months (not two first)
- when i select any range, dont jump to the range starting month, just stay on last months...

**Comment by dangrossman** [comment]
Here's where to find the code to change that for your requirements: https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L540

**Comment by achtan** [comment]
ok, thx
i am not familiar with how-to-extend-jqery-plugins-method can you point me to the right direction please... ? (i tried to google it, but with no luck)

**Comment by dangrossman** [comment]
I'm not sure why you're googling that? You're not "extending a jquery plugin", you're just editing the code in your copy of daterangepicker.js to work the way you want it to.
