### ISSUE TITLE
Extra week showing that doesn't belong to month

### ISSUE THREAD

**Issue by kalobhr** [dangrossman/daterangepicker#1802]
July 2018 for instance : the first week shown is the last week of June.  And then the last week shown under August 2018 is the first week of September. 

Is this deliberate (perhaps necessary to align the left and right months).

**Comment by dangrossman** [comment]
Yes, this is deliberate, why?

**Comment by dangrossman** [comment]
I don't recall 100% what I was thinking 6 years ago when I wrote the code, except that it was loosely based on the calendar in Windows (Windows 7 I guess?), in that each month has the same number of rows and dates from the previous/subsequent month fill in the gaps. Having the previous month be the first row of the current month, when the current month starts on a Sunday, is something that Windows does too. Nobody's ever questioned that before now.

![ss](https://user-images.githubusercontent.com/407706/43041798-eeedd0e8-8d38-11e8-91e1-39067c48a741.png)

**Comment by dangrossman** [comment]
Each month has the same number of rows, so dates from the previous/subsequent month fill in the gaps. 
 Having the previous month be the first row of the current month, when the current month starts on a Sunday, is something that Windows does too. Nobody's ever questioned that before now.

![ss](https://user-images.githubusercontent.com/407706/43041808-37151200-8d39-11e8-8787-3d47526ce645.png)

As for adding your custom number to the first column, I'd recommend just putting it in the same place the week numbers go in when that option is enabled, and use the same logic already used to determine what number to show. Add your code here:

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L770

**Comment by kalobhr** [comment]
Thanks Dan, I really appreciate you taking the time to respond so promptly.
