### ISSUE TITLE
persian-bootstrap-daterangepicker

### ISSUE THREAD

**Issue by mohamadsdg** [dangrossman/daterangepicker#1803]
hi @dangrossman
1) Why, when I install a package persian-bootstrap-daterangepicker from NPM , Inside it, the node module is installed ?

2) When I load the files into a page script, everything is right  ,
But when I want to import the files and bundle with webpack 
has many error 

But this is true for daterangepicker , and it's not a problem

@behrang
I used moment-jalaali you too
You can guide 

/* sample */
persin daterangepicker--mode bundle => http://pro.hamidteimouri.com/pro1/

daterangepicker -- mode bundle => http://pro.hamidteimouri.com/pro2/

daterangepicker -- mode script => http://pro.hamidteimouri.com/pro3/

persian daterangepicker -- mode script => http://pro.hamidteimouri.com/pro4/

**Comment by mohamadsdg** [comment]
@dangrossman

**Comment by dangrossman** [comment]
I don't know anything about any of this.

**Comment by behrang** [comment]
If it helps, moment-jalaali does not support requirejs out of the box. A workaround is provided in this issue: https://github.com/jalaali/moment-jalaali/issues/32.
