### ISSUE TITLE
How do I limit Costume Range by 2 months only? So that users can only select 60 days. 

### ISSUE THREAD

**Issue by mcfaith9** [dangrossman/daterangepicker#1804]

**Comment by dangrossman** [comment]
With the `maxSpan` option.

````
$('#element').daterangepicker({
    "maxSpan": {
        "days": 60
    },
    ...
});
````

**Comment by mmddistr** [comment]
A 2-month range doesn't always mean 60 days. Examples:

15 Jan 2019 to 15 Mar 2019 = 59 days
15 Feb 2019 to 15 Apr 2019 = 59 days
15 Jan 2020 to 15 Mar 2020 = 60 days (leap year)
15 Feb 2020 to 15 Apr 2020 = 60 days (leap year)
15 Mar 2020 to 15 May 2020 = 61 days
15 Apr 2020 to 15 Jun 2020 = 61 days
15 May 2020 to 15 Jul 2020 = 61 days
15 Jun 2020 to 15 Aug 2020 = 61 days
15 Jul 2020 to 15 Sep 2020 = 62 days
15 Aug 2020 to 15 Oct 2020 = 61 days
15 Sep 2020 to 15 Nov 2020 = 61 days
15 Oct 2020 to 15 Dec 2020 = 61 days
15 Nov 2020 to 15 Jan 2021 = 61 days

**Comment by dangrossman** [comment]
@mmddistr 

    "months": 2

Better?
