### ISSUE TITLE
custom date help

### ISSUE THREAD

**Issue by buddyy93** [dangrossman/daterangepicker#1812]
![image](https://user-images.githubusercontent.com/22981271/43999836-1246aa82-9e47-11e8-9c9f-e4de3a4a1338.png)

i wan to say some extra informations below the date, can someone tell me how to do it ? i read the documentations and found the isCustomDate configuration, but i'm not sure how to implement it either, please help, thank you

**Comment by dangrossman** [comment]
You would have to code that yourself, as there is no feature to add extra information below the date
