### ISSUE TITLE
Use daterangepicker without jquery in ReactJS

### ISSUE THREAD

**Issue by manoj016** [dangrossman/daterangepicker#1815]
I am using this in React with JQuery which leads an error called maximum update to the dom, so how can I implement this without jquery in react js??

Thank you

**Comment by dangrossman** [comment]
This is a jQuery plugin, it requires jQuery

**Comment by arpitprod** [comment]
I found [this](https://www.npmjs.com/package/react-advanced-datetimerange-picker) plugin for react based on this daterangepicker.
