### ISSUE TITLE
How to set Min_date and Max_date as like as setting start_date and end_date as given below

### ISSUE THREAD

**Issue by venkat-aadithan** [dangrossman/daterangepicker#1817]
$('#daterange').data('daterangepicker').setStartDate('03/01/2014');
$('#daterange').data('daterangepicker').setEndtDate('03/01/2014');

**Comment by highstone** [comment]
I just ran into this as well. See the comments in this issue: #1185

**Comment by venkat-aadithan** [comment]
@highstone  thanks!! :)
