### ISSUE TITLE
The newly created element cannot fail to trigger focus events

### ISSUE THREAD

**Issue by wind-lc** [dangrossman/daterangepicker#1819]
if (this.element.is('input') || this.element.is('button')) {
            this.element.on({
                'click.daterangepicker': $.proxy(this.show, this),
                'focus.daterangepicker': $.proxy(this.show, this),
                'keyup.daterangepicker': $.proxy(this.elementChanged, this),
                'keydown.daterangepicker': $.proxy(this.keydown, this) //IE 11 compatibility
            });
        } else {
            this.element.on('click.daterangepicker', $.proxy(this.toggle, this));
            this.element.on('keydown.daterangepicker', $.proxy(this.toggle, this));
        }
//It is recommended to delegate the event to document

**Comment by dangrossman** [comment]
I don't know what you're trying to say here
