### ISSUE TITLE
Local format option not working

### ISSUE THREAD

**Issue by highfly117** [dangrossman/daterangepicker#1822]
Hi, i cant seem to get local format to change to DD/MM/YYYY.

currently the date picker stays as MM/DD/YYYY no mater what i set local format to.

This the code copied from your generator and examples. Also this currently give an error as it says the startDate is in a different format to the format.

```
$(function() {
	  $('input[name="daterange"]').daterangepicker({
		singleDatePicker: true,
		local:{format: 'DD/MM/YYYY',
		},
		startDate:'09/24/2018',
		opens: 'left'
	  }, function(start, end, label) {
		console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
	  });
	});
```

**Comment by dangrossman** [comment]
The setting name is `locale` not `local`
