### ISSUE TITLE
Date rang picker fails if we want to select for more than 2 months 

### ISSUE THREAD

**Issue by revoorunischal** [dangrossman/daterangepicker#1825]

**Comment by nuryagdym** [comment]
I am facing same problem, in this library code in monthOrYearChanged() function this range is automatically selected: 
`
            if (isLeft) {
                this.leftCalendar.month.month(month).year(year);
                if (this.linkedCalendars)
                    this.rightCalendar.month = this.leftCalendar.month.clone().add(1, 'month');
            } else {
                this.rightCalendar.month.month(month).year(year);
                if (this.linkedCalendars)
                    this.leftCalendar.month = this.rightCalendar.month.clone().subtract(1, 'month');
            }`

**Comment by dangrossman** [comment]
That code determines what calendar months are displayed in the picker UI, not what dates are selected

It in no way prevents you from selecting more than two months apart
