### ISSUE TITLE
Out Of Month

### ISSUE THREAD

**Issue by andrewg211** [dangrossman/daterangepicker#1828]
ATM it's difficult to target date elements with CSS that are outise of the current month in the calendar.

Any chance of adding an 'out-of-month' class to dates that are "Out Of Month"

Just a small change to line 787 of daterangepicer.js
`//grey out the dates in other months displayed at beginning and end of this calendar
 if (calendar[row][col].month() != calendar[1][1].month())
 classes.push('off', 'out-of-month');

**Comment by stereokai** [comment]
This is very important.

Also, it is impossible to differentiate between dates that belong to the next (or previous) month, and between dates that are beyond the min or max date.

@dangrossman I am forking and submitting a PR

**Comment by dangrossman** [comment]
These dates now have their own CSS class to discern

**Comment by pallavpunhani** [comment]
Is there a way to disable the dates with this class (i.e. "ends")? I know there's a property invalidDate that is used to disable dates but I am not sure how to pass the dates outside of current month to it. 
Any help is greatly appreciated! Thanks a lot.
