### ISSUE TITLE
unlinked calendars suddenly become linked

### ISSUE THREAD

**Issue by softshape** [dangrossman/daterangepicker#1830]
1) Set linkedCalendars = false;
2) Select two different monts, say May on left and September on right;
3) June, 1 is disabled but clickable on the left calendar; click on it.

After you click on disabled cell on the left calendar, the right calendar resets to the next month (June in this example) as if it would be linked.

**Comment by dangrossman** [comment]
Feel free to submit a PR that fixes this if you'd like
