### ISSUE TITLE
fromLabel/toLabel not used

### ISSUE THREAD

**Issue by ianwremmel** [dangrossman/daterangepicker#1834]
The configurator implies daterangepicker accepts fromLabel and toLabel in the locale object, but these values aren't used anywhere in code. My use case requires that we display labels instead of the current date when no initial date is set.

**Comment by dangrossman** [comment]
These were labels within the date picking UI in a past version, not related to labels or placeholders on the text inputs of your own webpage.

Refer to this example for how to start with a blank input (which you can give a placeholder attribute or a label): http://www.daterangepicker.com/#example5

**Comment by ianwremmel** [comment]
I've got most of a code change ready to go that would honor those labels when startDate/endDate aren't set. Would you be interested in it if it works? (at the moment, it's causing an issue where the startDate needs to be clicked twice to be selected)

**Comment by dangrossman** [comment]
I don't quite know what you mean by honoring those labels. There's nothing "from" or "to" would go with in the current UI.

**Comment by ianwremmel** [comment]
in our use case, we'd like to display "Arrive - Depart" rather than "<today's date> - <tomorrow's date>" if `startDate` and `endDate` aren't set.

**Comment by zackchandler** [comment]
Here is an example of the UX benefits of providing custom labels (example taken from Airbnb):

![kapture 2018-09-10 at 12 09 44](https://user-images.githubusercontent.com/208/45318677-7c949e00-b4f2-11e8-9299-0b11bcd8fcd5.gif)

**Comment by dangrossman** [comment]
I could see that if this library supported two inputs, but it doesn't do that either atm, so there aren't two places to put two labels nor does it update anything when only one of the two dates is selected so far
