### ISSUE TITLE
 how to set any as a default in this date range picker

### ISSUE THREAD

**Issue by vinayo** [dangrossman/daterangepicker#1837]
"ranges": {
"Any": [
moment("2000-01-01 00:00:00");
moment().endOf('day');
],
[...other ranges here...]
}

please tell me how to set any as a default in this date range picker

**Comment by dangrossman** [comment]
To set "any" as the default, set the same dates as the `startDate` and `endDate` settings which define the initially selected range.

````
startDate: moment("2000-01-01 00:00:00"),
endDate: moment().endOf('day')
````
