### ISSUE TITLE
Question: How to use the calendar to select only years as range

### ISSUE THREAD

**Issue by ironhide0396** [dangrossman/daterangepicker#1840]
Might have been solved or answered previously but i read the documentation and couldnt the option to make sure that the calendar can be use to select only custom year field instead of date/month/year combo.

Thanks!

**Comment by dangrossman** [comment]
There's not an option for that.

You shouldn't put 1500 lines of calendar management code into your webpage when you don't need calendars.

Just put two `<select name="year">` boxes in your webpage.
