### ISSUE TITLE
Disbaling alwaysShowCalendar and disabling showCustomRangeLabel,not possible to remove "Today" range field

### ISSUE THREAD

**Issue by ironhide0396** [dangrossman/daterangepicker#1841]
While using custom ranges if we specify a set of ranges of our choice ,the calendar always pops up when we remove "Today" from our ranges list while having alwaysShowCalendar and showCustomRangeLabel as false.

**Comment by dangrossman** [comment]
The calendars are shown when the current date range does not match any of your predefined ranges. 

It sounds like you want to show a list of labels on your webpage and have a user choose one of them. You don't need any actual date picking or calendar functionality. In that case, you should not be using this library. It's 1500+ lines of code you have absolutely no use for. Code the list into your webpage...
