### ISSUE TITLE
Disable particular dates

### ISSUE THREAD

**Issue by venkat-aadithan** [dangrossman/daterangepicker#1843]
How to disable particular set of dates in date_range_picker?

ex:(2018-05-01,2018-05-03,2018-05-08,2018-05-10,...)

**Comment by dangrossman** [comment]
The `isInvalidDate` setting allows you to disable dates on the calendars. You provide a function and it is passed each date in the calendar. Return true if it should be disabled.

````
$('#yourelement').daterangepicker({
  isInvalidDate: function(date) {
    //compare to your list of dates, return true if date is in the list
  }
});
````

**Comment by venkat-aadithan** [comment]
Thanks Bro!!! it working fine :+1:
