### ISSUE TITLE
Possibility to open the picker without any preselected date/range

### ISSUE THREAD

**Issue by agross** [dangrossman/daterangepicker#1844]
Hi,

Thank you for creating the picker! Is it possible to have the initial picker to open without any date range being preselected? I tried `startDate: undefinded, endDate: undefined`, but that still causes a range starting and ending today to be preselected (I also use `min/maxDate`).

Thanks,

Alex

**Comment by dangrossman** [comment]
No that is not possible with this library, sorry.
