### ISSUE TITLE
how to change the size of customPane

### ISSUE THREAD

**Issue by zhaoxinjie** [dangrossman/daterangepicker#1845]
i use daterangepicker in a pane and put the pane into a iframe, but when i click custom, the ifrme overload the apply button, so i can't confirm the range date
![image](https://user-images.githubusercontent.com/16410073/45794994-f8010700-bccb-11e8-9fe7-c1e859e84171.png)
![image](https://user-images.githubusercontent.com/16410073/45795016-11a24e80-bccc-11e8-9146-5dc9511bc84f.png)

**Comment by dangrossman** [comment]
I'm not sure what you're describing. You can use the `parentEl` option to change what part of the document the picker is attached to when it's created.

By the way, you are using version 2 of this library, which was first released in 2015. We are currently on version 3.0.3.

**Comment by zhaoxinjie** [comment]
sorry for my poor english, now the question is when i open the custom option, next time drop down, i don't want it to show custom pane, i want to show the default, is there an setting to avoid this? look forward your response, thank you.
