### ISSUE TITLE
Uncaught TypeError: t is not a function

### ISSUE THREAD

**Issue by wilecoyte78** [dangrossman/daterangepicker#1849]
$('input[name="datetimes"]').daterangepicker({
				timePicker: true,
				minDate: moment(),
				startDate: moment().startOf('hour').add(1, 'hour'),
				endDate: moment().startOf('hour').add(2, 'hour'),
				locale: {
					format: 'YYYY-MM-DD HH:mm:ss'
				}
			});

This is what causing the issue this.startDate=t().startOf("day")

**Comment by dangrossman** [comment]
I just copied and pasted that into the console at http://www.daterangepicker.com (with the selector changed to `#config-demo`) and received no errors.

**Comment by wilecoyte78** [comment]
Where is the console to try out out own code on http://www.daterangepicker.com ?

I did figure out my issue I had moment.js load after daterangerpicker.

**Comment by dangrossman** [comment]
Press CTRL+SHIFT+J or F12 in your browser to open the console on any webpage.
