### ISSUE TITLE
Feature request: set max-height and max-width of the picker

### ISSUE THREAD

**Issue by alexcombessie** [dangrossman/daterangepicker#1851]
I have tried many things with CSS but I cannot seem to make it work:
<img width="1173" alt="screen shot 2018-09-26 at 13 48 38" src="https://user-images.githubusercontent.com/4739848/46080870-ea97c100-c192-11e8-8f42-9841503471fa.png">
Is it something that should be done in JS? If not, which class should I define height for?

**Comment by dangrossman** [comment]
It should be done in CSS. You're going to have to reduce the size of the calendar date cells to make it fit in your 300px height.
