### ISSUE TITLE
Can't select dates if "autoUpdateInput" is false

### ISSUE THREAD

**Issue by jasonmorehead** [dangrossman/daterangepicker#1854]
If I set "autoUpdateInput" to "false" then the selected date doesn't appear in the text field. The calendar appears and I can navigate around in the calendar just fine, but if I click on a date, the calendar closes and nothing happens.

This happens regardless of whether "singleDatePicker" is set to "true" or "false."

To try and troubleshoot this, I followed the instructions in [this comment](https://github.com/dangrossman/daterangepicker/issues/1793#issuecomment-403661118). If I put this in the console, everything seems to work fine:

```
$('input[name="datefilter"]').daterangepicker({ singleDatePicker: true });
```

But if I put this in the console, then the above behavior happens, and I can't actually select a date:

```
$('input[name="datefilter"]').daterangepicker({ autoUpdateInput: false, singleDatePicker: true });
```

FWIW, I'm using v3.0.3 with jQuery v3.3.1.

**Comment by dangrossman** [comment]
That is the intended result. autoUpdateInput: false means "do not update the input for me". If you want the selection to be put in your input, remove this option.
