### ISSUE TITLE
The position of month and year is reversed when customizing date range

### ISSUE THREAD

**Issue by RickyZhou2** [dangrossman/daterangepicker#1859]
In our culture the date format is YYYY MM, everything has been localized except the position year and month in the pop up dialog, which is reversed.
![_20181015114344](https://user-images.githubusercontent.com/25873383/46929198-eca5bf00-d070-11e8-91b0-3f4b918451f5.png)

The position is hard code in the js file:
```javascript
var dateHtml = this.locale.monthNames[calendar[1][1].month()] + calendar[1][1].format(" YYYY");
```
It should follow the local setting.

**Comment by dangrossman** [comment]
If there's a way to make it follow the local setting automatically, please share or make a PR using it.
