### ISSUE TITLE
Daterangepicker dropdown position at fixed div

### ISSUE THREAD

**Issue by kvkv** [dangrossman/daterangepicker#1860]
I am using Daterangepicker at my application header. The header is fixed position , when we scroll the content the header is in fixed on top position only. I added the daterangepicker on header. 

1. open the daterangepicker on header
2.scroll down or up the body content
3. the datepicker dropdown also moved base on scroll.

This is the issue i am facing. In bootstrap dropdowns are not move on the fixed header. It attaches the dropdown box only for fixed div also. 

But in this daterangepicker dropdown menu is moving.

Please help me for this issue.

**Comment by dangrossman** [comment]
Edit daterangepicker.css as needed

**Comment by kvkv** [comment]
Can you please give the details for changes in datereangepicker.css file.
