### ISSUE TITLE
Set singleDatepicker date

### ISSUE THREAD

**Issue by andre-dw** [dangrossman/daterangepicker#1863]
Is there a way to set the date of the singleDatePicker.
When using one of these methods:
```
$('#daterange').data('daterangepicker').setStartDate('03/01/2014');
$('#daterange').data('daterangepicker').setEndDate('03/31/2014');
```
The date is set to an range again.

**Comment by dangrossman** [comment]
Set the start date and end date to the same date. You can also change settings the same way you set them initially.
