### ISSUE TITLE
Make separate date inputs from v2 as optional feature

### ISSUE THREAD

**Issue by smajl** [dangrossman/daterangepicker#1865]
Hi, first of all thanks for nice UI lib. Since we switched from v2 to v3 we noticed that users started to complain a lot about "not able to edit dates manually". It's apparently very confusing for them to use the main input and that they lost date inputs inside the popup itself where everything was nicely wrapped for them.

Could these date inputs be brought back and made available through a new setting to optionally display them, please? Maybe it could be simple as taking parts of code from v2 and hiding them behind a feature flag? Thanks in advance.

**Comment by dangrossman** [comment]
Why would you switch from v2 to v3 if your users were happy with v2? You can have two date inputs in your app by continuing to use v2, or by putting two date inputs in your app and attaching a single date picker to each one. I am not going to be adding any major new features to this library in the near future.
