### ISSUE TITLE
Allow selection of just month or year

### ISSUE THREAD

**Issue by thiagouxca** [dangrossman/daterangepicker#1866]
It would be very useful a way to select just a range of months (ex.: 01/2018 - 10/2018) and a range of years (ex.: 2016 - 2018).

To this the visualization of the calendars could have the options of bootstrap datepicker, like these:
**Month selector** (of an year)
<img width="222" alt="screen shot 2018-10-31 at 17 45 59" src="https://user-images.githubusercontent.com/35309227/47817620-e1bb8180-dd34-11e8-93e9-772afbd90092.png">
________________________________________________________________________
**Year selector** (of a dacade)
<img width="219" alt="screen shot 2018-10-31 at 17 46 06" src="https://user-images.githubusercontent.com/35309227/47817626-e54f0880-dd34-11e8-8e5b-769559c28d4d.png">
________________________________________________________________________

### Benchmark
Example of other plugin documentation:
https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#maxviewmode

Another way is by defining the date format, ex.: MM/YYYY or just YYYY.

Would anyone like these options of view mode limits?
Is it difficult to implement it or adapt this feature to the DateRangePicker?

**Comment by dangrossman** [comment]
I don't see how those grids of years are a better user experience than simply having a `<select>` on your webpage. People know how to pick things from lists, and select lists have built-in native support and good accessibility. I don't plan to add this feature.

**Comment by thiagouxca** [comment]
As a user experience designer, I can say to you: there is much more cognitive charge in a list of 100 items to scroll and select than in a scoped options as the examples that I've shown you.

Let other users of this plugin think about it and tell us here ¯\_(ツ)_/¯

**Comment by GustavoSD** [comment]
Thanks for such an amazing plugin @dangrossman . I agree with @thiagouxca , this feature would be really helpful. Would be better to have this functionality with the same feel & look and in the same plugin with the functionality of selecting just one or multiple dates.

**Comment by shams-144** [comment]
Thanks for such an amazing plugin @dangrossman . I agree with @thiagouxca , this feature would be really helpful.
