### ISSUE TITLE
applyButtonClasses, cancelButtonClasses not apply

### ISSUE THREAD

**Issue by shenau92** [dangrossman/daterangepicker#1868]
When set custom class name for propertys cancelButtonClasses, cancelButtonClasses, DOM not generate  custom class for them.

**Comment by dangrossman** [comment]
This option is working. You can test at http://www.daterangepicker.com by putting this in the console then clicking on the Configuration Generator demo box:

````
$('#config-demo').daterangepicker({ cancelButtonClasses: 'btn-danger' });
````

The cancel button turns red as a result of the custom class which was applied to the DOM.

**Comment by shenau92** [comment]
In live demo  http://www.daterangepicker.com it works OK, but in react component it not generate class name.

**Comment by xjpalma** [comment]
replace cancelButtonClasses to cancelClass
replace applyButtonClasses to applyClass

**Comment by lakinmohapatra** [comment]
> cancelClass

This one worked for me. thank you .
