### ISSUE TITLE
Issues installing in meteor project

### ISSUE THREAD

**Issue by nosizejosh** [dangrossman/daterangepicker#1875]
Trying to install this plugin into a meteor project via [atmosphere](https://atmospherejs.com/dangrossman/bootstrap-daterangepicker) leading to conflicting package version number and a hard dependecy on bootstrap 3. 
package version after installing is 2.* while current version here is 3.0.3
also my project uses boostrap 4 so the dependecy on bootstrap 3 ( which is not showing in this current version 3.0.3 but exists in versions 2.*) conflict with bs4 in my project.

Can anyone help?
- how do I install this latest version via atmosphere?
- does this version also have a hard dependency on bs3?

**Comment by dangrossman** [comment]
I don't know anything about meteor or atmosphere, sorry. I did not put it there. The current version of this library has no dependency on Bootstrap.
