### ISSUE TITLE
Daterangepicker not showing in BS4 modal

### ISSUE THREAD

**Issue by nosizejosh** [dangrossman/daterangepicker#1876]
I have spent a number of days trying all suggested ways to get this to work but it will just not work. I am using current version of daterangepicker and bs4. 

my modal code below;

> <div class="modal fade" id="dateRangeModal" tabindex="-1" role="dialog" aria-labelledby="dateRangeModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            
            <div class="modal-body">
              <h5 class="modal-title" id="exampleModalLongTitle">Availability</h5>        
                <p> 
                  show calendar
                  <input type="text" name="birthday" value="" />
                </p>        
            </div>            
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div> 

and daterangepicker code follows;

>     $('input[name="birthday"]').daterangepicker({ parentEl: $('#dateRangeModal'), showDropdowns: true,});
 // tried this as well

>    $('input[name="birthday"]').daterangepicker({ parentEl: $('dateRangeModal'), showDropdowns: true,});

nothing i have tried so far has worked. please help

**Comment by dangrossman** [comment]
Here's a fiddle with your HTML and javascript code in it. The picker shows up fine.

https://jsfiddle.net/ywn1z69p/1/

**Comment by nosizejosh** [comment]
Thanks for your reply. I am using meteor and though you may not know about meteor, your reply made me realize I was calling daterangepicker too late and at the wrong place. I now call it together with the click action that creates the modal. Challenge now is that, when the modal first runs, the  daterangepicker still doesn't work, but when you close and open the modal again, then the picker shows up. 
What i'm I  missing? can anyone help please?
