### ISSUE TITLE
Range picker with unlikend calendars, left calendar for startDate and right for endDate

### ISSUE THREAD

**Issue by victornpb** [dangrossman/daterangepicker#1877]
The current range goes from 5 to 16 if I want to change the 5 to 4 for example, I have to click both 4 and then 16 instead I could just click the left calendar on 4.

Left calendar always control the startDate, and right calendar always set the minDate.
![image](https://user-images.githubusercontent.com/3372598/49082906-2f42e580-f232-11e8-9f58-ae7ea5830535.png)

is this possible, or there is any workaround?

**Comment by dangrossman** [comment]
You could have two inputs and attach a single date picker to each one. Then the two dates are selected entirely separately. That is your only option.

**Comment by victornpb** [comment]
It is just inconvenient to have to re implement the whole range logic from scratch if going with standalone inputs. But ok, I'm just wondering if there's any reason for it being implemented that way, and if you would accept a PR that implements this behavior through an option?

**Comment by victornpb** [comment]
I really appreciate the clarification, in that case I will revaluate my requirements.
Thanks
