### ISSUE TITLE
how to set selected date in datepicker?

### ISSUE THREAD

**Issue by callmedavron** [dangrossman/daterangepicker#1881]
Hi, i want to set the selected date in datepicker, but i don't want use minDate, so how can i set the date which will be selected in datepicker!
Thanks!

**Comment by dangrossman** [comment]
`startDate` and `endDate` set the initially selected date range

http://www.daterangepicker.com/#options

**Comment by callmedavron** [comment]
But i don't want range, I don't want to limit user actions, i want show datepicker without range and only selected date

**Comment by dangrossman** [comment]
You asked to set the selected date in the date picker. These are the options which set the selected date in the date picker. They are not limits.

**Comment by callmedavron** [comment]
i understand, thanks, i find solution in your answers!
