### ISSUE TITLE
Setting default dates in input value instead of script

### ISSUE THREAD

**Issue by Mercyware** [dangrossman/daterangepicker#1885]
Hi, i am currently using your daterangepicker. Its great.

However, i would love to set default dates in the input like this

` <input type="datetime" name="daterange" id="date_@d.TVStationId" class="daterange" value="10/10/2008 - 20/12/2009" />`

Instead of the script overriding this. Is this possible ?

**Comment by dangrossman** [comment]
Yes, that's already supported, works just like that.
