### ISSUE TITLE
Picking single date r

### ISSUE THREAD

**Issue by chrisfildes** [dangrossman/daterangepicker#1887]
Hi,
I'm trying to pick a single date on the daterange picker. When I select just one date, the apply button becomes hidden. 

I'm guessing this is available, as you can already pick single date ranges from the predefined 'Today' or 'Yesterday' option.
 
All the best
Chris

**Comment by chrisfildes** [comment]
Hi Dan

Thanks for that. I don't think I explained it correctly...

We are trying to to click on a single date and then hit apply on the date range picker as well as 2 dates.

ie if a user wants to search for items within a date range or on a particular day.

The ranges option allows us to do this by including 'Today' and 'Yesterday'.

Thanks in advance if there is a workaround.

All the best
Chris

**Comment by dangrossman** [comment]
There is not an option or work around that makes it work like that.

**Comment by chrisfildes** [comment]
Ok, thanks Dan. I really love your component and find it so much better than other date pickers. I really do want to use it for my project.

I've completed a small workaround, that allows people to select a single date from the date range picker (after all a single date is still a date range for many use cases)

1. New version if click apply always sets end date to start date if not set

clickApply: function(e) {

            if (!this.endDate) {
                this.endDate = this.startDate.clone();
            }

            this.hide();
            this.element.trigger('apply.daterangepicker', this);
        },

2. New version of updateFormInputs allows apply button to be shown if just one date available

 updateFormInputs: function() {

            if (this.startDate && !this.endDate) {
                this.container.find('button.applyBtn').removeAttr('disabled');
            }
            else {
                if ((this.startDate.isBefore(this.endDate) || this.startDate.isSame(this.endDate)) ) {
                    this.container.find('button.applyBtn').removeAttr('disabled');
                } else {
                    this.container.find('button.applyBtn').attr('disabled', 'disabled');
                }
            }
 
        },

Thought this might be something people might find useful (if only as a quick hack when they have a business user demand for this) - perhaps something like this as a configurable option might be a really nice add-on to those of us who need the flexibility?

Regards,
Chris

**Comment by venarius** [comment]
@chrisfildes just had the same problem and your "hack" works great!
@dangrossman can this be integrated as a full feature into the `daterangepicker`? At react dates they had a similar problem (https://github.com/airbnb/react-dates/issues/24) and being able to also select only one date makes perfect sense.

**Comment by pallavpunhani** [comment]
@chrisfildes @venarius I have the same problem. Would either of you know if it's possible to achieve this in your own component? i.e. without touching the author's original code. I didn't want to do that for long term code-maintenance purposes. Thanks for your help!
