### ISSUE TITLE
Inconsistent endDate, off by 999ms

### ISSUE THREAD

**Issue by phazei** [dangrossman/daterangepicker#1890]
In the code, in many places when setting the endDate, the `moment.endOf('day')` is used.

This will set it to `2018-12-25T07:59:59.999Z` initially for example if nothing is applied.  But then if you select an end date that's the same, it will the set it to `2018-12-25T07:59:59.000Z`

This causes issues when checking if dates with `moment.isSame()`

That happens because in the `setEndDate` method for whatever reason sets it like so:
`this.endDate = this.endDate.add(1,'d').startOf('day').subtract(1,'second');`
instead of
`this.endDate. this.endDate.endOf('day')`
which is simpler and used more often

Could line 491 be changed to use endOf('day') instead of subtracting a second?

**Comment by dangrossman** [comment]
That code was added by someone to fix another bug, so it's there for a purpose

`isSame()` takes a second parameter you should use 

https://momentjs.com/docs/#/query/is-same/

**Comment by phazei** [comment]
Nice double entendre
date.isSame(endDate, 'second')

I was looking into #1587, and the fix for the moment bug is finally going to be committed in the next release of moment:
https://github.com/moment/moment/pull/4338#issuecomment-446857625

I was going to resubmit the PR while maintaining the same fix for #1587 by simply changing the line to:
> this.endDate = this.endDate.add(1,'d').startOf('day').subtract(1,'ms');
as the original submitter probably just didn't notice the difference.

Then I went about testing it with the Brazil timezone and the dates mentioned and this is the result:

> moment.tz("2016-10-15","America/Sao_Paulo").endOf('day').format()
> "2016-10-15T22:59:59-03:00"
> 
> moment.tz("2016-10-15","America/Sao_Paulo").add(1,'day').startOf('day').subtract(1,'s').format()
> "2016-10-14T23:59:59-03:00"
> 
> moment.tz("2016-10-15","America/Sao_Paulo").add(1,'day').startOf('day').subtract(1,'ms').format()
> "2016-10-14T23:59:59-03:00"
> 
> moment.tz("2016-10-16","America/Sao_Paulo").endOf('day').format()
> "2016-10-17T00:59:59-02:00"
> 
> moment.tz("2016-10-16","America/Sao_Paulo").add(1,'day').startOf('day').subtract(1,'ms').format()
> "2016-10-16T23:59:59-02:00"

<img width="721" alt="screen shot 2018-12-26 at 11 18 51 am" src="https://user-images.githubusercontent.com/431395/50455114-d635a280-0900-11e9-876e-cb53186d02d9.png">


So, PR #1588 really only fixes 1 day, while breaking others.  That 'fix' causes 2016-10-15 to be set as the 14th, though does fix 2016-10-16 to not be the 17th.  So it just shifts the problem over by one day.  It also creates inconsistency for every single other date by 999ms.  So it has zero positive benefits.  It's really a complicated timezone math issue that is not possible to trivially fix here.  Fortunately, the fix will be in moment *soon*™

**Comment by jdivy** [comment]
I agree with @phazei assessment - this just broke us in a pretty bad way.
