### ISSUE TITLE
No way to "apply" on enter

### ISSUE THREAD

**Issue by phazei** [dangrossman/daterangepicker#1891]
If the picker is set to only update on apply, which is the only way to get around not applying on outsideClick, then there's no way to trigger apply when enter is pressed on the field if the date is being typed in manually.

When enter is pressed, which is pretty universal for apply, the hide function is called which triggers the change function.  But there's no way to trigger apply in that case unless it's put in the change callback.  But it can't be put in the change call back because that breaks the fix for clicking outsideClick.

I tried manually adding another keydown handler that will trigger 'apply' only when the picker is open, but hide is called first so isShowing is already false when it's called.

**Comment by dangrossman** [comment]
Sounds like you need to edit the code to make it work the way you want. You can delete outsideClick, or have it do something else, or put your desired code in the hide function, etc.
