### ISSUE TITLE
Trying to bower install asks for username & password

### ISSUE THREAD

**Issue by designhata** [dangrossman/daterangepicker#1892]
So I have one bower package named `ng-bs-daterangepicker` which has this package listed as dependency. When I try to do `bower install`, installation gets stuck on this package & asks me for username & password.

This is some of the install output:

`bower cached        https://github.com/sfos/bootstrap-daterangepicker.git#v1.3.23.1
bower validate      v1.3.23.1 against https://github.com/sfos/bootstrap-daterangepicker.git#v1.3.23.1
bower cached        https://github.com/twbs/bootstrap.git#3.0.3
bower validate      3.0.3 against https://github.com/twbs/bootstrap.git#~3.0.0
bower cached        https://github.com/moment/moment-timezone.git#0.3.1
bower validate      0.3.1 against https://github.com/moment/moment-timezone.git#^0.3.1
bower cached        https://github.com/dangrossman/bootstrap-daterangepicker.git#1.3.17
bower validate      1.3.17 against https://github.com/dangrossman/bootstrap-daterangepicker.git#1.3.17
bower cached        https://github.com/twbs/bootstrap.git#3.4.0
bower validate      3.4.0 against https://github.com/twbs/bootstrap.git#^3.0.0
bower cached        https://github.com/dangrossman/bootstrap-daterangepicker.git#2.1.27
bower validate      2.1.27 against https://github.com/dangrossman/bootstrap-daterangepicker.git#^2.0.0
bower download      https://github.com/BrandwatchLtd/daterangepicker/archive/v1.6.0.tar.gz
Username for 'https://github.com':`

On input I get following message:

> Authentication failed for 'https://github.com/euskadi31/bower-angular-unstable.git/'

I tried installing this package separately too & output was same.
Where is this `bower-angular-unstable` package dependency coming from? And how can I avoid this?

**Comment by phazei** [comment]
I don't think `bower-angular-unstable` has anything at all to do with this plugin.

And I'd suggest perhaps trying https://github.com/fragaria/angular-daterangepicker
Neither have been updated in years, but it works for the most part with drp 3.0.3

**Comment by designhata** [comment]
Thanks Adam for the reply.

If `bower-angular-unstable` isn't in this package as a dependency, then how can I trace back from where this package is being called?

I don't have much knowledge on bower dependencies & package system. So it'd be very helpful if someone can guide me on how to remove this package dependency as I can't proceed with `bower install` for any of my projects.

**Comment by dangrossman** [comment]
I don't know anything about bower either (I do not publish to their repository), but if this is holding you up, can't you just download the .js file you need and put it in your project yourself?
