### ISSUE TITLE
Range date picker calendar jumping on the start date month after selecting end date from next months

### ISSUE THREAD

**Issue by agsanandb** [dangrossman/daterangepicker#1894]
Hi Guys,

I've one more issue with the range date picker. 

Here is the scenario:

Whenever I click on the end date in the range date picker, the calendar is jumping to the start date month.

It is working for the same month because there is no month change in the calendar.
But, when I click on the date from the upcoming months(for example my start date is 1st Jan and End date is 6th of August) then the calendar jumps to start date month(1st Jan).

Please refer the video link: https://www.useloom.com/share/1bf1aba5921c4b65bc20b35ecbe1a9ca

My requirement is, it should stick on the end date month.

Please share the solution if you have any.

Thanks.

**Comment by dangrossman** [comment]
Use `linkedCalendars: false`
