### ISSUE TITLE
Chosing the minDate, it happened to "undefinedInvalid date"

### ISSUE THREAD

**Issue by JayInnn** [dangrossman/daterangepicker#1902]
This is the bug:
![image](https://user-images.githubusercontent.com/31987743/50823632-5fbc8a00-136f-11e9-8a8f-dd72fda70dbf.png)

I suggest u should pay more attention on minDate. In this picture, this plugin cannot parse minDate format so it dispalyed "undefinedInvalid date". Why cannot parse minDate, let me show u my code!

This is my code:
`$(".time-range-picker").daterangepicker({
    timePicker: true,
    timePicker24Hour: true,
    timePickerIncrement: 30,
   
 locale: {
        format: "YYYY-MM-DD HH:mm",
        applyLabel: "确定",
        cancelLabel: "取消",
        customRangeLabel: "自定义"
    },
    minDate: moment().subtract(7, "days"),
    maxDate: moment(),
    endDate: moment().endOf("day"),
    ranges: {
        "最近1小时": [moment().subtract(1, 'hours'), moment()],
        "最近3小时": [moment().subtract(3, 'hours'), moment()],
        "最近6小时": [moment().subtract(6, 'hours'), moment()],
        "今天": [moment().startOf("day"), moment().endOf("day")]
    }
});`

I found that becaus of "timePickerIncrement: 30", it would happened to this bug. Every time, maxDate is moment()--current_time, and minDate is 7 date less than maxDate; but owing to "timePickerIncrement: 30", it cannot parse minDate format. For example, now is 14:33, so maxDate is 14:33, but minDate cannot parse 14:33 so minDate show the 14:__ as in the picture, thus when this plugin parse minDate, it happened to this bug, and this bug lasted 15min--14:31~14:46. Specifically, every hour has 15min bug-time!!!

I think in this code minDate may not match timePickerIncrement, So i try to reset timePickerIncrement;
this is the resetting code:
`$(".time-range-picker").daterangepicker({
    timePicker: true,
    timePicker24Hour: true,
    timePickerIncrement: 1,
   
 locale: {
        format: "YYYY-MM-DD HH:mm",
        applyLabel: "确定",
        cancelLabel: "取消",
        customRangeLabel: "自定义"
    },
    minDate: moment().subtract(7, "days"),
    maxDate: moment(),
    endDate: moment().endOf("day"),
    ranges: {
        "最近1小时": [moment().subtract(1, 'hours'), moment()],
        "最近3小时": [moment().subtract(3, 'hours'), moment()],
        "最近6小时": [moment().subtract(6, 'hours'), moment()],
        "今天": [moment().startOf("day"), moment().endOf("day")]
    }
});`

After that, this new code avoided the bug. Imagically that!!!

I just used a foolish method to solve this problem, and i hope someone can find the problem in the source code and try to solver it.

**Comment by JayInnn** [comment]
has one solution but need to edit source code to increase "robust"

**Comment by brightgarden** [comment]
#1927 Made a fix for my similar issue.
