### ISSUE TITLE
Hide/Disable days 

### ISSUE THREAD

**Issue by rafaelcastrocouto** [dangrossman/daterangepicker#1903]
Considering the amount of positive feedback from my answer to this stack-overflow question:
https://stackoverflow.com/questions/30618462/daterangepicker-show-year-and-months-only

And that it's been asked here in the issues before:
https://github.com/dangrossman/daterangepicker/issues/1347
https://github.com/dangrossman/daterangepicker/issues/578
https://github.com/dangrossman/daterangepicker/issues/103

Maybe it would be good to provide a `hideDays` option that would hide the specific table and maybe some extra options like the defaut day. Just tell me if you need help, I could code this myself and make a PR.

**Comment by dangrossman** [comment]
Why are you including 1000+ lines of calendar management javascript to put two `<select>` tags in a dropdown on your webpage? Why not just write the 20 lines of HTML code? Serious question.

**Comment by rafaelcastrocouto** [comment]
Well then I guess we could make an wiki page or just a fiddle to help those that are in need of those 20 lines of code. I would never grab a lib for that, as I said, I'm just trying to help with a recurrent problem.

**Comment by CodeCurosity** [comment]
I am surprised that is there is no option to disable days of the week, i would like to disable the weekends and also i want to limit time picker from 9 AM to 5 PM, these are 2 very basic options missing from such a nice picker.

**Comment by dangrossman** [comment]
@CodeCurosity There is an option to disable days of the week (`isInvalidDate`) and I am surprised you left this message as a comment on someone else's unrelated issue.
