### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by baileykm** [dangrossman/daterangepicker#1908]
1. The default range is "today", but in some case, the empty value is necessary. For example, when I use it to choose a date range for retrieve data, but keep it empty mark the date range is not a search criteria.

2. If I want to assign an initial value for the input field by element.val(...) directly (but not by options),  the daterangepicker trigger the 'change' event twice, and it causing confusion.

I am trying to solve the above problem, you can see it in the attach file. It seems to work, but I am not sure if it is robust.
[daterangepicker.js.zip](https://github.com/dangrossman/daterangepicker/files/2775762/daterangepicker.js.zip)

**Comment by dangrossman** [comment]
This example on the documentation page solves both your problems:

http://www.daterangepicker.com/#example5
