### ISSUE TITLE
daterangepicker.js can't be imported in a vue component

### ISSUE THREAD

**Issue by cyanl77** [dangrossman/daterangepicker#1909]
My project is based on webpack and vue. When importing daterangepicker.js into a component, the console printed: TypeError: $(...).daterangepicker is not a function. I finally found that no matter wether I import or require it,  it always run codes in line 10 to 16. So I exchange the judgement order of  conditions for AMD and Node/Browserify and solved the error.

I don't exactly know the principle behind my way of solution.But I thought maybe there's a bug in judgement logic.

**Comment by bmarwane** [comment]
I use daterangepicker

**Comment by bmarwane** [comment]
I use daterangepicker in a vue component here is what i did :  

- Add jquery and moment dependencies 

```
yarn add jquery moment
```
After doing that you could create your component like the example below : 

```
<template>
  <div>
    <div ref="daterange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
      <i class="icon ic-Calendar-Icon" />&nbsp;
      <span>{{ formattedResult }}</span>
      <i class="fa fa-caret-down" />
    </div>
  </div>
</template>

<script>
import $ from 'jquery';
import 'daterangepicker/daterangepicker.js';
import 'daterangepicker/daterangepicker.css';

import moment from 'moment';

export default {
  props: {
    start: {
      type: String,
    },
    end: {
      type: String,
    },
  },
  mounted() {
    let startDate;
    let endDate;
    if (this.start && this.end) {
      startDate = moment(this.start, 'DD/MM/YYYY');
      endDate = moment(this.end, 'DD/MM/YYYY');
    } else {
      startDate = moment().subtract(29, 'days');
      endDate = moment();
    }

    const onDateSelected = (start, end) => {
      this.$emit('change', {
        startDate: start.format('DD/MM/YYYY'),
        endDate: end.format('DD/MM/YYYY'),
      });
    };
    $(this.$refs.daterange).daterangepicker(
      {
        startDate: startDate,
        endDate: endDate,
        ranges: {
          'Depuis 1 mois': [moment().subtract(1, 'month'), moment()],
          'Depuis 3 mois': [moment().subtract(3, 'month'), moment()],
          'Depuis 6 mois': [moment().subtract(6, 'month'), moment()],
          'Depuis 1 an': [moment().subtract(1, 'year'), moment()],
        },
      },
      onDateSelected
    );
  },

  computed: {
    formattedResult() {
      if (!this.start && !this.end) return '';

      return this.start + ' - ' + this.end;
    },
  },
};
</script>
```

In this example the component takes the range from two props ( start and end) and dispatches an event with the chosen range.

Here is a usage example of my component : 

```
    <UiDateRange @change="handleChange" :start="startDate" :end="endDate" />
```

Hope you find the example helpful.

**Comment by cyanl77** [comment]
> I use daterangepicker in a vue component here is what i did :
> 
> * Add jquery and moment dependencies
> 
> ```
> yarn add jquery moment
> ```
> After doing that you could create your component like the example below :
> 
> **filename: DateRange.vue**
> 
> ```js
> <template>
>   <div>
>     <div ref="daterange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
>       <i class="icon ic-Calendar-Icon" />&nbsp;
>       <span>{{ formattedResult }}</span>
>       <i class="fa fa-caret-down" />
>     </div>
>   </div>
> </template>
> 
> <script>
> import $ from 'jquery';
> import 'daterangepicker/daterangepicker.js';
> import 'daterangepicker/daterangepicker.css';
> 
> import moment from 'moment';
> 
> export default {
>   props: {
>     start: {
>       type: String,
>     },
>     end: {
>       type: String,
>     },
>   },
>   mounted() {
>     let startDate;
>     let endDate;
>     if (this.start && this.end) {
>       startDate = moment(this.start, 'DD/MM/YYYY');
>       endDate = moment(this.end, 'DD/MM/YYYY');
>     } else {
>       startDate = moment().subtract(29, 'days');
>       endDate = moment();
>     }
> 
>     const onDateSelected = (start, end) => {
>       this.$emit('change', {
>         startDate: start.format('DD/MM/YYYY'),
>         endDate: end.format('DD/MM/YYYY'),
>       });
>     };
>     $(this.$refs.daterange).daterangepicker(
>       {
>         startDate: startDate,
>         endDate: endDate,
>         ranges: {
>           'Depuis 1 mois': [moment().subtract(1, 'month'), moment()],
>           'Depuis 3 mois': [moment().subtract(3, 'month'), moment()],
>           'Depuis 6 mois': [moment().subtract(6, 'month'), moment()],
>           'Depuis 1 an': [moment().subtract(1, 'year'), moment()],
>         },
>       },
>       onDateSelected
>     );
>   },
> 
>   computed: {
>     formattedResult() {
>       if (!this.start && !this.end) return '';
> 
>       return this.start + ' - ' + this.end;
>     },
>   },
> };
> </script>
> ```
> 
> In this example the component takes the range from two props ( start and end) and dispatches an event with the chosen range.
> 
> Here is a usage example of my component :
> 
> **inside another component**
> 
> ```
>     <UiDateRange @change="handleChange" :start="startDate" :end="endDate" />
> ```
> Hope you find the example helpful.

**Comment by cyanl77** [comment]
> I use daterangepicker in a vue component here is what i did :
> 
> * Add jquery and moment dependencies
> 
> ```
> yarn add jquery moment
> ```
> After doing that you could create your component like the example below :
> 
> **filename: DateRange.vue**
> 
> ```js
> <template>
>   <div>
>     <div ref="daterange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
>       <i class="icon ic-Calendar-Icon" />&nbsp;
>       <span>{{ formattedResult }}</span>
>       <i class="fa fa-caret-down" />
>     </div>
>   </div>
> </template>
> 
> <script>
> import $ from 'jquery';
> import 'daterangepicker/daterangepicker.js';
> import 'daterangepicker/daterangepicker.css';
> 
> import moment from 'moment';
> 
> export default {
>   props: {
>     start: {
>       type: String,
>     },
>     end: {
>       type: String,
>     },
>   },
>   mounted() {
>     let startDate;
>     let endDate;
>     if (this.start && this.end) {
>       startDate = moment(this.start, 'DD/MM/YYYY');
>       endDate = moment(this.end, 'DD/MM/YYYY');
>     } else {
>       startDate = moment().subtract(29, 'days');
>       endDate = moment();
>     }
> 
>     const onDateSelected = (start, end) => {
>       this.$emit('change', {
>         startDate: start.format('DD/MM/YYYY'),
>         endDate: end.format('DD/MM/YYYY'),
>       });
>     };
>     $(this.$refs.daterange).daterangepicker(
>       {
>         startDate: startDate,
>         endDate: endDate,
>         ranges: {
>           'Depuis 1 mois': [moment().subtract(1, 'month'), moment()],
>           'Depuis 3 mois': [moment().subtract(3, 'month'), moment()],
>           'Depuis 6 mois': [moment().subtract(6, 'month'), moment()],
>           'Depuis 1 an': [moment().subtract(1, 'year'), moment()],
>         },
>       },
>       onDateSelected
>     );
>   },
> 
>   computed: {
>     formattedResult() {
>       if (!this.start && !this.end) return '';
> 
>       return this.start + ' - ' + this.end;
>     },
>   },
> };
> </script>
> ```
> 
> In this example the component takes the range from two props ( start and end) and dispatches an event with the chosen range.
> 
> Here is a usage example of my component :
> 
> **inside another component**
> 
> ```
>     <UiDateRange @change="handleChange" :start="startDate" :end="endDate" />
> ```
> Hope you find the example helpful.

Thanks for your answer. I try your code out and it did work!  The only difference is my way to include jQuery,  in which I imported rest of the files but used script label in html for jQuery including. Maybe multiple ways for including can't be used together.
