### ISSUE TITLE
singleDatePicker without value

### ISSUE THREAD

**Issue by mctdi** [dangrossman/daterangepicker#1916]
I try to setup a daterangepicker with a singleDatePicker without value (visible for the user).
When It will click a value, value will be displayed in the daterangepicker

I tried without success this code

```
 $('#searchSamplesBuildDatePicker').daterangepicker({
                    autoUpdateInput: false,
                    autoApply: true,
                    singleDatePicker: true
});
```

tried also

 $('#searchSamplesBuildDatePicker').daterangepicker({
                    autoUpdateInput: false,
                    autoApply: true,
                    singleDatePicker: true
});

**Comment by mctdi** [comment]
don't want to need to click apply...

**Comment by dangrossman** [comment]
Same code works with `autoApply: true`.

**Comment by muriiloandrade** [comment]
Have to create an event to populate the input field is kinda bizarre... Wouldn't be a more elegant approach just pass an option "initially empty"? The behaviour that we have with autoUpdateInput is already ok, the problem is that not all date fields are required in pages. 🤷‍♂️
