### ISSUE TITLE
Getting the current value of the input as two dates. 

### ISSUE THREAD

**Issue by littlefyr** [dangrossman/daterangepicker#1921]
If you get the date range element and call `val()` on it you get a string. But if I don't want a string, if I want two dates because I'm going to use them as dates, I have to parse them twice (once to split the string on the separator and again to get the two dates). Its likely that you are keeping an internal copy of the actual date values since all that text parsing would be unnecessarily slow. 

You already have setter functions for both dates, its oddly inconsistent not to have getter functions. Of course the jQuery approach would be to use `picker.startDate(someDate)` to set it and `picker.startDate()` to get it.

**Comment by dangrossman** [comment]
Whenever a date range is chosen, the two dates, as date objects, are provided to your callback function.

See example number 1: http://www.daterangepicker.com/#example1

The current selection is also stored in two variables you can access as properties of the picker object. 

See example number 5: http://www.daterangepicker.com/#example5
