### ISSUE TITLE
Custom styles or any way to use ranges and time functionality for custom buttons

### ISSUE THREAD

**Issue by ggepenyan** [dangrossman/daterangepicker#1923]
Need to get something like this
![screen shot 2019-02-27 at 12 05 36 pm](https://user-images.githubusercontent.com/17830568/53474996-30c9b700-3a88-11e9-81cd-a401c8f48c60.png)

but this is what I'm able to get.
![screen shot 2019-02-27 at 12 07 46 pm](https://user-images.githubusercontent.com/17830568/53475052-5d7dce80-3a88-11e9-83e0-3e63f87cbee4.png)

Is there any way for me  to get it? I think even if it's not possible, There must be options to be able to customise all these things

**Comment by dangrossman** [comment]
You would have to edit the code to achieve that. Luckily, you can edit the code.

**Comment by ggepenyan** [comment]
Yea, I did that. I forked package and did what I needed. Thanks for your good work!
