### ISSUE TITLE
highlight specific dates in calendar

### ISSUE THREAD

**Issue by Cartmaniac** [dangrossman/daterangepicker#1924]
Is there a way to tell daterangepicker to highlight specific dates (maybe put a specific css class on them)?

**Comment by dangrossman** [comment]
Yes, that is the `isCustomDate` option. Here's how to highlight April 15 with a specific CSS class:

    <style>
      .red {
        background: #c00;
      }
    </style>

    <script>
        $('#picker').daterangepicker({
          isCustomDate: function(date) {
            if (date.isSame('2019-04-15', 'day')) return 'red';
          }
        });
    </script>

**Comment by kouloughli-hemza** [comment]
Can you please explain how can we change date text instead of adding css class ?

**Comment by dangrossman** [comment]
There's not a setting for that. You would need to code that yourself.

**Comment by kouloughli-hemza** [comment]
> There's not a setting for that. You would need to code that yourself.

Can you please guide me on how to start ?

**Comment by kouloughli-hemza** [comment]
what i mean is can we do it for multiple dates ?
for exemple
        if (date.isSame('2019-04-15', 'day')) return 'red';
instead of single date , we use array of dates

**Comment by dangrossman** [comment]
Yes, you can do that. Compare `date` to your array of dates in your function.

**Comment by kouloughli-hemza** [comment]
This is what i did so far but it's not working when looping my array of dates : 
`                isCustomDate: function(date) {

                    var x = moment(date,"DD-MM-YYYY");

                    $.each(array[0].departures, function(key, value){
                       if (x.isSame( moment(value.date_departure,"YYYY-MM-DD"))){
                           return 'red';
                       }
                   });

                }`
