### ISSUE TITLE
The month March not appear

### ISSUE THREAD

**Issue by lucascco** [dangrossman/daterangepicker#1933]
The month of march is not appear. The bug is happen in all libs that depend this lib datarangerpicker.

**Comment by dangrossman** [comment]
What? 
![ss](https://user-images.githubusercontent.com/407706/54782321-f53c8b80-4bf4-11e9-93c0-5b7d14084a8f.png)

**Comment by lucascco** [comment]
![image](https://user-images.githubusercontent.com/6581094/54783102-42bdf600-4bff-11e9-8d9e-7ae01075228e.png)

But when I go to mode anonymous, all work well, that were a cache problem, I just cleaned it to resolve.

I really don't know what happened, but thank a lot to your answer.  =)
