### ISSUE TITLE
Dropdown calendar randomly shows undefinedInvalid date and NaN.

### ISSUE THREAD

**Issue by neeraj87** [dangrossman/daterangepicker#1934]
Sometimes the dropdown calendar randomly shows **undefinedInvalid date** and **NaN**.

<img width="732" alt="Screenshot 2019-03-28 at 4 35 37 PM" src="https://user-images.githubusercontent.com/7267014/55154167-24657680-517a-11e9-9271-b4e422b28035.png">

As mentioned in issue #1902 the possible reason could be the usage of minDate option. However in my case it displays this error even on the inputs not using minDate.
This is the sample code of the above image:

```
$('input#booking_date_single').daterangepicker({
    minDate: new Date(),
    drops: 'down',
    timePicker: true,
    timePickerIncrement: 30,
    autoUpdateInput: false,
    showDropdowns: true,
    locale: {
        format: 'MM/DD/YYYY hh:mm:ss A'
    }
}, function(start, end, label) {
    //doing some ajax stuff here
}).on('apply.daterangepicker', function(ev, picker) {
    $(this).val(picker.startDate.format('MM/DD/YYYY hh:mm A') + ' - ' + picker.endDate.format('MM/DD/YYYY hh:mm A'));
});

```

If I close the page and then revisit it some time later, everything is restored and then again after using the site for sometime the error reappears. 

I do not see any JS errors in the console.

Any idea what might be causing this to happen and what is the possible solution to this?

**Comment by dangrossman** [comment]
I think this is a bug with `timePickerIncrement` (which only manifests when the current clock time is after your increment) and I just merged a PR that claims to fix it, so please update and see if that fixes it for you.
