### ISSUE TITLE
[feature req] Present only one time picker

### ISSUE THREAD

**Issue by jarodium** [dangrossman/daterangepicker#1937]
Hello

I would like to submit a feature request, to only show 1 timepicker only.
This has already been brought up in #716 4 years ago.

Reasoning for the request:
1) The library from Eonasdan ( https://github.com/Eonasdan/bootstrap-datetimepicker/issues ) is frozen, meaning there will be no updates to it, not mentioning the fact it has support only for BootStrap 3.
2) Keep time/date libraries to minimum, due to the obvious performance boost in having fewer scripts and css's loaded.
3) Daterangepicker has a SingleDate option so I think it should provide a SingleTime option as well.

**Comment by dangrossman** [comment]
You mean you want to use this library to display a time picker alone? Please do not load 5000 lines of calendar management code into your webpage to display a `<select>` or two on the page. Not everything on your webpage requires an external library.
