### ISSUE TITLE
singleDatePicker prev month arrow not displayed (Firefox)

### ISSUE THREAD

**Issue by Lukerayn3r** [dangrossman/daterangepicker#1940]
Hi,

I'm not sure if this is happening for anyone else or if it unique to me.

I have a singledatepicker inside a bootstrap modal which does not display the previous month arrow. I inspected the elements and there is no code in the `<th></th>` tags, the tag is just empty.

I am using @version: 2.1.19 so this could be the reason.

This is only happening on firefox it is working everywhere else. 

```
$('#pdf_summary_capture_end').daterangepicker({
    locale: {
      format: 'DD-MM-YYYY'
    },
    singleDatePicker:   true,
    startDate:          pdf_summary_capture_end,
    minDate:            moment('01-01-2015'),
    maxDate:            moment()
}, function(start, end, label) {
    // we are done here
});
```

This might not be an issue it could just be something I have done but I thought it was worth asking.

**Comment by dangrossman** [comment]
This is why:

    moment('01-01-2015').format('YYYY-MM-DD');
    "Invalid date"
