### ISSUE TITLE
Published version 3.0.4 installs npm as dependency?

### ISSUE THREAD

**Issue by ngyikp** [dangrossman/daterangepicker#1941]
https://cdn.jsdelivr.net/npm/bootstrap-daterangepicker@3.0.4/package.json

Line 28

**Comment by dangrossman** [comment]
I don't know why that's there

It's not present here on github or on my computer

https://github.com/dangrossman/daterangepicker/blob/v3.0.4/package.json

**Comment by dangrossman** [comment]
It's also not present here: 

https://cdn.jsdelivr.net/npm/daterangepicker/package.json

Perhaps it's because you're specifying a release in your URL?
