### ISSUE TITLE
Not working in bootstrap tab

### ISSUE THREAD

**Issue by yudiznilay** [dangrossman/daterangepicker#1943]
First of all thanks for the plugin. Recently found an issue while working on it. Can you please help me?
**Code**
There is a common form used in more than one tab. Form structure
![code](https://user-images.githubusercontent.com/40666649/56798861-53ccd900-6835-11e9-832f-cfff3e7612ff.png)

**Scenario**
There are two tabs 
First tab which has only form element.
The second tab which has some content before form element.

**Issue related to positioning**
1) Open picker of the first tab positions correctly
2) Open picker of the second tab positions incorrectly.

So, how to use the same form and code in multiple tabs?

**Comment by dangrossman** [comment]
`parentEl: '.form'` is probably not useful since `.form` does not uniquely identify the parent element... you re-use that class name in multiple forms according to your description.

**Comment by yudiznilay** [comment]
Okay, thank you for the help.
