### ISSUE TITLE
reactjs and daterangepicker

### ISSUE THREAD

**Issue by grinsteindavid** [dangrossman/daterangepicker#1946]
Hi there. There is any tutorial to integrate daterangepicker with reactjs? It was hard even to find some tutorials about this plugin

**Comment by dangrossman** [comment]
I don't know anything about React. 

I did Google and found this for you: 

https://github.com/skratchdot/react-bootstrap-daterangepicker

https://react.rocks/example/react-bootstrap-daterangepicker

**Comment by arpitprod** [comment]
I found [this](https://www.npmjs.com/package/react-advanced-datetimerange-picker) plugin for react based on this daterangepicker.
