### ISSUE TITLE
Increase custom range limit?

### ISSUE THREAD

**Issue by hamzabinamin** [dangrossman/daterangepicker#1947]
The custom range only works across two months. May till June. If I want to select from May to August or May to September, I can't do that. Is there a way to change that?

**Comment by dangrossman** [comment]
There is no such limit. Use the arrow keys at the top of the calendars to scroll to any month you want, hundreds of years in either direction.

**Comment by dangrossman** [comment]
There is no such limit. Click on a date in May, click the arrow at the top of the calendar to scroll to September, then click on a date in September. You've now selected a range from May to September.

**Comment by hamzabinamin** [comment]
@dangrossman I have tried that. Doesn't work. If I click on Jan 1st for example and then if I go to May, if I select on 30th May, it takes me back to Feb.

I am using the custom range option in the predefined range example here:
http://www.daterangepicker.com/#ex1

**Comment by dangrossman** [comment]
It "takes you back to Feb" because it always displays two sequential months, but Jan 1st to May 30 is selected.

**Comment by hamzabinamin** [comment]
In my case the range isn't selected as well.

**Comment by dangrossman** [comment]
Yes it is. This library does not behave differently on your computer than everyone else's.

**Comment by dangrossman** [comment]
https://screencast-o-matic.com/watch/cqhfo2ZHCz
