### ISSUE TITLE
Number of months you jump on next/previous

### ISSUE THREAD

**Issue by germanitxu** [dangrossman/daterangepicker#1953]
Is there an option or method to set the amount of months the user will jump to? I am expecting something like (Jan, Feb) -> (Mar, Apr) instead of (Jan, Feb) -> (Feb, Mar).
Edit: linkedCalendars is set as true, so the months change together when clicking next or previous.
Thanks ^^

**Comment by dangrossman** [comment]
No

**Comment by germanitxu** [comment]
In that case, since i downloaded the plugin in my project, will it be fine if I change your original code and try to add this feature?

**Comment by dangrossman** [comment]
Yes, you can make any changes you want
