### ISSUE TITLE
Invalid SSL certificate for www.daterangepicker.com

### ISSUE THREAD

**Issue by sgdesmet** [dangrossman/daterangepicker#1957]
Not an issue with the library and you're probably aware of this, but the SSL certificate for https://www.daterangepicker.com/ is invalid.
Probably won't be an issue for most, except a few (like me) that use something like HTTPS Everywhere.

**Comment by dangrossman** [comment]
I just added it to Cloudflare so it should get an HTTPS cert within a few hours. Thanks.
