### ISSUE TITLE
Cannot create property 'guid' on string '.prev'

### ISSUE THREAD

**Issue by Tsyklop** [dangrossman/daterangepicker#1959]
I use `daterangepicker 3.14.1` with `ReactJS 16.8.6` and `jQuery 3.3.1` and `moment.js 2.24.0`.
```
daterangepicker($(this.dateInputRef.current), {
    "singleDatePicker": true,
    "minYear": 2018,
    "showISOWeekNumbers": true,
    "maxSpan": {
        "days": 7
    },
    "locale": {
        "format": "DD/MM/YYYY",
        "separator": " - ",
        "applyLabel": "Ввод",
        "cancelLabel": "Отмена",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "Вс",
            "Пн",
            "Вт",
            "Ср",
            "Чт",
            "Пт",
            "Сб"
        ],
        "monthNames": [
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь"
        ],
        "firstDay": 1
    },
    "linkedCalendars": false,
    "showCustomRangeLabel": false,
    "startDate": "05/11/2019",
}, function(start, end, label) {
    //var years = moment().diff(start, 'years');
});
```

But when datepicker initialize I get next error:

```
jquery.js:4393 Uncaught TypeError: Cannot create property 'guid' on string '.prev'
    at Object.add (jquery.js:4393)
    at HTMLDivElement.<anonymous> (jquery.js:4349)
    at Function.each (jquery.js:311)
    at jQuery.fn.init.each (jquery.js:162)
    at on (jquery.js:4348)
    at jQuery.fn.init.on (jquery.js:5013)
    at DateRangePicker (daterangepicker.js:277)
```

I tried use this without `ReactJS` and get same error.
Example here: https://jsfiddle.net/jhe4gy5z/1/

**Comment by dangrossman** [comment]
I'm afraid I don't know anything about ReactJS, but I can tell you why your other example doesn't work. The daterangepicker constructor takes an options object and a callback as parameters, not a page element and options.

Wrong:

    daterangepicker($('input[name="startDay"]'), {...

Right:

    $('input[name="startDay"]').daterangepicker({...

https://jsfiddle.net/jrod4ezc/

**Comment by Tsyklop** [comment]
But `$('input[name="startDay"]').daterangepicker({...` is not working too.

Your variant throw next error: `daterangepicker is not a function`.

**Comment by dangrossman** [comment]
There's no error on the fiddle I linked.

**Comment by Tsyklop** [comment]
@dangrossman this error happens on with me with reactjs.

**Comment by dangrossman** [comment]
Like I said, I don't know anything about ReactJS. You won't get code for that here, sorry.

**Comment by Tsyklop** [comment]
I Solve this error with ReactJS. Thanks

**Comment by mkumar028** [comment]
@Tsyklop May I know how you fix this issue? I am also facing the same issue when adding this library to a React project.

**Comment by kevinmershon** [comment]
This is almost certainly an issue of people trying to use this plugin from within TypeScript. That was my issue and I resolved it by pulling out all the import statements to a dedicated little js module.

**Comment by jonathandarchy** [comment]
daterangepicker shouldn't be initialized as a function.
`daterangepicker($('input[name="startDay"]'), {...`
it's a class
`new daterangepicker($('input[name="startDay"]'), {...`

that solved it for me.
