### ISSUE TITLE
Incorrect 24 hour time 

### ISSUE THREAD

**Issue by sarthaksavvy** [dangrossman/daterangepicker#1960]
When selecting time as 0:18 (or any time after midnight) for 24hour system, it will display as 24:30 which is incorrect.
How to correct it.

This should give time as 0:18

![Screenshot 2019-05-21 at 12 26 35 AM](https://user-images.githubusercontent.com/41295276/58045101-21c24480-7b5f-11e9-9146-01c935277a14.png)

**Comment by dangrossman** [comment]
What's your date format string? The default one doesn't include time at all.
