### ISSUE TITLE
DateRangePicker not focusing endDate

### ISSUE THREAD

**Issue by Maksiemens** [dangrossman/daterangepicker#1964]
DateRangePicker not focusing endDate after selecting startDate
In Vue, this function works
https://innologica.github.io/vue2-daterange-picker/

**Comment by dangrossman** [comment]
I don't understand your question.

**Comment by Maksiemens** [comment]
Sorry, let me talk about my problem. I like your plugin and I use it

Problem:
When I select date in left calenter, then select in right calendar. Datepicker 'jump' to start month and show me start date.

Expect:
I want, that datepicker will show me selected end date or dont jump to start(first, left) calendar.
Like in Vue adaptation, what based on yours plugin

Could you help me to solve this problem?

**Comment by dangrossman** [comment]
Include `linkedCalendars: false` in your options when you create the picker.

**Comment by Maksiemens** [comment]
https://i106.fastpic.ru/big/2019/0604/c3/404b265fe0da2baa9831d35a3a3acdc3.png
![image](https://user-images.githubusercontent.com/26347041/58896673-25c59900-86ff-11e9-9033-830669b4362c.png)
that's not what i wanted

**Comment by dangrossman** [comment]
It's exactly how the one on the webpage you linked works, because that's the option it's using. If you want something else, you'll have to program it yourself.

**Comment by dangrossman** [comment]
![ss](https://user-images.githubusercontent.com/407706/58908503-c0fa4680-86de-11e9-8991-fa3c410db92d.png)

**Comment by Maksiemens** [comment]
In yours calender, if two month shown in same window. Its okay, it works good. But if first calendar Feb, and second calendar for example May. The picker does jumping to first calendar, it doesn't stay in last date(second calendar). How did in that picker, that based on yours. If i have to program it for myself, how i can do it?
It related with render right calendar?

![image](https://user-images.githubusercontent.com/26347041/58932666-4298b580-876d-11e9-8e4c-bff4cc244ed5.png)
