### ISSUE TITLE
daterangepicker: Hour and minute dropdown not working in firefox when calendar inside Bootstrap modal

### ISSUE THREAD

**Issue by NimeshDhruve** [dangrossman/daterangepicker#1965]
_Originally posted by @NimeshDhruve in https://github.com/dangrossman/daterangepicker/issues/1311#issuecomment-498767272_

I can reproduce this issue (in June 2019) with Bootstrap v4, Firefox 67.0.1
Below is the CodePen URL exhibiting this issue. Please use Firefox as it surely works in Google Chrome.
https://codepen.io/nimesh/pen/zQXOao?editors=1010

Creating new issue as the previous one is closed.

**Comment by dangrossman** [comment]
The other issue you linked contained a fix (for your page, not to this library).. remove tabindex from modal element.

**Comment by patel33hardik** [comment]
If you don't want to loss tabindex functionality use following:

```
$("#yourDatepickerId").daterangepicker({
    parentEl: "#BootstrapModalId .modal-body"            
})
```
