### ISSUE TITLE
How to initial value in new format

### ISSUE THREAD

**Issue by InfinityKn** [dangrossman/daterangepicker#1970]
I want to initial value in DD/MM/YYYY but it's show invalid date

------ Code ------

	<input type='text' id='date' value='17/06/2019'>

	<script>
		$(function() {
			$('input[name="date"]').daterangepicker({
				singleDatePicker: true,
				showDropdowns: true,
				autoUpdateInput: false,
				locale: {
					cancelLabel: 'Clear'
				},
				autoApply: true
			});

			$('input[name="date"]').on('apply.daterangepicker', function(ev, picker) {
				$(this).val(picker.startDate.format('DD/MM/YYYY'));
			});

			$('input[name="date"]').on('cancel.daterangepicker', function(ev, picker) {
				$(this).val('');
			});
		});
	</script>

**Comment by dangrossman** [comment]
Add the desired format string to your locale setting
````
			locale: {
				cancelLabel: 'Clear',
                                format: 'DD/MM/YYYY'
			},

````

**Comment by InfinityKn** [comment]
> Add the desired format string to your locale setting
> 
> ```
> 			locale: {
> 				cancelLabel: 'Clear',
>                                 format: 'DD/MM/YYYY'
> 			},
> ```
