### ISSUE TITLE
dynamically change singleDatePicker on and off

### ISSUE THREAD

**Issue by patel33hardik** [dangrossman/daterangepicker#1971]
Hi,
Thanks for sharing such a useful plugin.
I want to use your datepicker on a single HTML element. Can I update its state dynamically when user select radio button range or single date? I want a single date and range based on the selected radio button.
i.e. I can be done by
 
> singleDatePicker: false, or true

which gives me only single date picker(pop up) and on the range, It has to give me two on the same element.

**Comment by dangrossman** [comment]
You can re-create the picker with the new `singleDatePicker` option when your radio button is clicked.

**Comment by patel33hardik** [comment]
Thanks, 
I did that same, it works
