### ISSUE TITLE
Dropdown Active Issue

### ISSUE THREAD

**Issue by Insankamil** [dangrossman/daterangepicker#1973]
1. First, click the filed default selected last 7 days

![image](https://user-images.githubusercontent.com/15888925/60155425-b4619d80-9807-11e9-8355-f03f0758a0e2.png)

2. Click the custom range in the list and after I click cancel button the dropdown is close.

3. Click the field the last 7 days and custom range also show. how to fix the issue

![image](https://user-images.githubusercontent.com/15888925/60155551-1f12d900-9808-11e9-99eb-4f35d3986230.png)

**Comment by dangrossman** [comment]
You could add some code to the `show()` or `hide()` method to check if a predefined range is selected and hide the calendars I suppose. Nobody else has complained about it working like this in 7 years, so I think I'll not change the behavior.
