### ISSUE TITLE
Custom range - prev/next month results in text selection in Edge

### ISSUE THREAD

**Issue by nchorrigan** [dangrossman/daterangepicker#1975]
In Edge browser only, when you go to select a custom date range and click on either the prev or next month buttons the browser will start to select the text when you next click on a date in the calendar.

![2019-07-01 13_26_29-Window](https://user-images.githubusercontent.com/3297787/60436466-ffaeee00-9c03-11e9-968b-7fc5153bee36.png)

**Comment by dangrossman** [comment]
I'm not able to reproduce that at http://www.daterangepicker.com/ in Edge 42.

**Comment by nchorrigan** [comment]
Just tried it on another machine and could replicate it on the examples page (see screenshot).  Testing in Edge 44

![image](https://user-images.githubusercontent.com/3297787/60456114-503c4080-9c30-11e9-95d8-90385418c856.png)

**Comment by dangrossman** [comment]
I have all Windows Updates installed and still only have Edge 42, so I can't even attempt to reproduce this. Feel free to submit a PR if you figure it out.

**Comment by zrelja** [comment]
Hey @dangrossman, I also managed to recreate this bug as @nchorrigan.
The bug was recreated on Edge 44.17763.831.0
Any luck with this?
