### ISSUE TITLE
jQuery.fn.removeAttr no longer sets boolean properties: disabled

### ISSUE THREAD

**Issue by lilHermit** [dangrossman/daterangepicker#1982]
According to jquery-migrate this was depreciated in jquery 3
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnremoveattr-no-longer-sets-boolean-properties

**Comment by dangrossman** [comment]
I merged the PR which updates this

**Comment by elvynmejia** [comment]
Which version of daterangepicker is this on?
