### ISSUE TITLE
setStartDate  and setEndDate do not update calendars

### ISSUE THREAD

**Issue by pallavpunhani** [dangrossman/daterangepicker#1983]
I am trying to update the startDate and endDate by using:
picker.data('daterangepicker').setStartDate('03/03/2019');
picker.data('daterangepicker').setEndDate('04/04/2019');

I can see the updated dates in picker.data('daterangepicker'), however, the calendar itself doesnt update i.e. the selected dates on calendar don't update.

Could you please help me with this?

**Comment by Bighamster** [comment]
when you use:

$('#datepicker').data('daterangepicker').setStartDate(moment(begin_at,'DD-MM-YYYY'));
$('#datepicker').data('daterangepicker').setEndDate(moment(end_at,'DD-MM-YYYY'));

to update input value:
    $('#datepicker').data('daterangepicker').updateElement();

to update calender even if view is hidden:
    $('#datepicker').data('daterangepicker').updateView();

**Comment by pallavpunhani** [comment]
thanks a lot! @Bighamster

**Comment by sportity** [comment]
Can this be added to examples and documentation?
Example code in docs (http://www.daterangepicker.com/#options) doesn't mention it at all.
