### ISSUE TITLE
Switching between months doesn't update date selected

### ISSUE THREAD

**Issue by sts-ryan-holton** [dangrossman/daterangepicker#1985]
When I select a different month, or navigate via the prev/next arrows at the top of the date picker, and select a day, it then closes the datepicker, I then have to open the datepicker a second time for it to update the value.

**Comment by dangrossman** [comment]
It doesn't behave like that at http://www.daterangepicker.com so this is probably a side effect of something else on your specific webpage

**Comment by sts-ryan-holton** [comment]
@dangrossman Nope, we've confirmed in our codebase that this plugin doesn't work correctly when changing months.

**Comment by dangrossman** [comment]
What does "confirmed in our code base" mean? Here are two videos of me selecting a different month, selecting a day, and the value being updated without reopening the picker a second time.

![ex1](https://user-images.githubusercontent.com/407706/63181050-66a22e00-c01d-11e9-978f-97e50ea72b7c.gif)

![ex2](https://user-images.githubusercontent.com/407706/63181054-69048800-c01d-11e9-8ec4-4c56c1911b8d.gif)
