### ISSUE TITLE
How to pick only startDate and Fix endDate as moment()

### ISSUE THREAD

**Issue by ch667sg** [dangrossman/daterangepicker#1991]
Hi I have some question about code

I want to get only range startdate to moment
I can use `singleDatePicker` but i want to show range when pick it

![image](https://user-images.githubusercontent.com/51559134/61680328-53a88080-ad33-11e9-89dd-20f707ea5c12.png)

How can I do this?

**Comment by dangrossman** [comment]
There's not a setting for that, so you would have to program that behavior yourself
