### ISSUE TITLE
Empty week bug

### ISSUE THREAD

**Issue by amirhabibi** [dangrossman/daterangepicker#1992]
Hi guys,

When you add  `"firstDay": 1`

An full empty unneeded week is created (in red in the screenshot). This seems to be a bug:

<img width="518" alt="Capture d’écran 2019-07-26 à 10 47 34" src="https://user-images.githubusercontent.com/1267664/61940004-daa86380-af94-11e9-95ab-36d5acda0849.png">

When you remove it, things go "normal" and this never happens: 

<img width="527" alt="Capture d’écran 2019-07-26 à 10 47 52" src="https://user-images.githubusercontent.com/1267664/61940041-ef84f700-af94-11e9-8f1a-7153d956a5fc.png">

Thanks for your help

**Comment by dangrossman** [comment]
That happens even if `firstDay` is not changed. The entire month is still visible, it's just a matter of whether the "empty week" is at the beginning or end of the calendar. If you dislike this, feel free to share different code for generating the calendar.
