### ISSUE TITLE
Add support for minSpan to force startDate != endDate

### ISSUE THREAD

**Issue by fede91it** [dangrossman/daterangepicker#1994]
How to prevent the user from selecting an end date equal to the start date? I would need to set some sort of `minSpan` parameter just like `maxSpan` does for the maximum span limit.

**Comment by dangrossman** [comment]
There is not a `minSpan` option so you'll have to code that requirement yourself.

**Comment by fede91it** [comment]
Is there a possibility that this option will be implemented?

**Comment by JeroneGagliano** [comment]
It would be very useful to have a minSpan.  One use case is that of selecting a date range for a chart and the chart will not make sense or display oddly if user selects less than X days of data.

**Comment by dangrossman** [comment]
If you can code a minSpan option and thoroughly test it with all of the other options, I would be happy to accept that pull request. There is nobody actively developing this library. I wrote it in 2012 and it does everything I personally need already.

**Comment by summonerriftofficial** [comment]
is it will be available ?

**Comment by saionachi** [comment]
+1 on making minSpan option..It would be very helpful
