### ISSUE TITLE
Disable Current Date highlight

### ISSUE THREAD

**Issue by thoughtAddict** [dangrossman/daterangepicker#1995]
Apologies if this has already been answered, but I could not find any mention in the documentation or this issue list.

We use the option "autoUpdateInput: false" and keep our start/end dates blank, (therefore the input is rendered blank).    When clicking on the _datarangepicker_ element, we have two months displayed, allowing our customers to pick their own range.

The current date is highlighted however, and this is confusing some of our customers in that they think it's the "start" date.   They go to pick what they think is the "end" date of the range, (really the "start"), and then get confused as to why it's not working.

![Selection_322](https://user-images.githubusercontent.com/784384/62163976-5b869880-b2d0-11e9-8489-def90b090c8a.png)

Any way to disable the current date highlight?

Thanks

Jon

**Comment by dangrossman** [comment]
No. The selected date range is always highlighted, and there is always a selected date range.
