### ISSUE TITLE
Disabled dates outside of month

### ISSUE THREAD

**Issue by pallavpunhani** [dangrossman/daterangepicker#1996]
I want to disable the dates that are outside of the month (i.e. the ones with classes "off, ends"). I know there's a property invalidDate that is used to disable dates but I am not sure how to pass the dates outside of current month to it. 
Any help is greatly appreciated! Thanks a lot.

**Comment by dangrossman** [comment]
Can you use `minDate` and `maxDate` and set them to the first and last day of the month you want available for selection? Can you hide the dates you don't want visible with CSS? I don't know what you're hoping to achieve or why.

**Comment by pallavpunhani** [comment]
Hi @dangrossman , thanks for the quick reply. 

As of now, the dates outside the month can be clicked. This is slightly confusing to the user since the dates with class "ends" don't exactly belong to that particular month. 

I am trying to disable these dates i.e. make them non-clickable; same as the dates > maxDate. (Yes, I can hide them with css but they will still be clickable). :/

**Comment by dangrossman** [comment]
Sorry, I don't understand how it's "confusing". If you look at the bottom right corner of your screen, there's probably a Windows task bar there, with today's date. If you click on that date, up pops a calendar for the month of July. It also has some of August at the end of the calendar, and those dates are clickable just like the ones in July. Been that way on every computer all of your users have used since 1995 or so. Do you want August 1st to be not clickable if they press the right arrow so that August is the main calendar on their screen? Or only when it's at the end of July's calendar?

**Comment by pallavpunhani** [comment]
Hi Dan, 

Only when it's at the end of July's Calendar. 

Further explanation:
When I click on August 8 in July's Calendar (Windows), it does not select the date in august :
![image](https://user-images.githubusercontent.com/8124504/62175522-05cfe180-b30c-11e9-97ed-8ce3285c78ce.png)

However, in the picker, when we select August date at the end of July, it SELECTS the date in August's calendar (which is confusing to the user):
![image](https://user-images.githubusercontent.com/8124504/62175634-5e06e380-b30c-11e9-843f-9f55b008a3b0.png)

**Comment by dangrossman** [comment]
Then you'll need to edit the code to reflect the behavior you want. There is not an option for this. You cannot make August 9th unselectable on the left but selectable on the right with any setting.

**Comment by pallavpunhani** [comment]
@dangrossman Can't this be accomplished by adding "disabled" class to "off, ends"? I am guessing other people using the picker might benefit from this as well since it's hard to distinguish between values out of range and values outside of month. Thanks again!

**Comment by fanjieqi** [comment]
@pallavpunhani It could be solved by adding css:
```css
.daterangepicker td.off {
  visibility: hidden;
}
```
