### ISSUE TITLE
Manual input an invalid date

### ISSUE THREAD

**Issue by yamifr07** [dangrossman/daterangepicker#1997]
When I set an invalid date manually in the input (e.g. asdasd), and call input.data('daterangepicker').startDate; it returns a valid date while the input displays "asdasd".  So I'm sending a "random" value to the server because the user hasn't entered a valid date. The same occurs when the maxDate is for example 01/01/2011 and manually enter 02/02/2012, the function returns 01/01/2011 while the input displays a greater value.

**Comment by dangrossman** [comment]
I can't reproduce that. When I type "asdasd" and then exit the input, it reverts to the previous valid date. If I type a date which is greater than maxDate then exit the input, it reverts to the maxDate.

**Comment by yamifr07** [comment]
<img width="429" alt="Captura de Pantalla 2019-08-01 a la(s) 19 42 29" src="https://user-images.githubusercontent.com/284215/62332079-86b9e500-b494-11e9-8699-0719741408c4.png">

I entered 08/12/2018 but calendar display 29/07/2018 (the max)

**Comment by dangrossman** [comment]
The blue outline suggests that your cursor is still in the "Fecha de nacimiento" input box. It will update when you click somewhere else to reflect the July 29 selection.

**Comment by yamifr07** [comment]
I upload a second image that displyas the final input value. Using 3.0.5

**Comment by yamifr07** [comment]
Using autoUpdateInput false to start with empty value

**Comment by dangrossman** [comment]
If you set `autoUpdateInput: false` you will need to manage or validate the value of your input yourself.
