### ISSUE TITLE
Weird behaviour of prev button, only 'partly' clickable

### ISSUE THREAD

**Issue by brusselsregular** [dangrossman/daterangepicker#1998]
Hi,

First of all thanks for creating this awesome picker!

I'm having a weird issue with the prev button...it's only 'partly' clickable. The user thinks it's not clickable because you have to click a bit 'left of the button' to click it.

I made a sall screencast so you can check out this behaviour: https://www.youtube.com/watch?v=WyHcn0iLwO8&feature=youtu.be

Weirdly enough the 'next' button works as expected, it's only the prev button 

- Using the latest version of the picker
- Using Vue.js  (the picker is mounted within Vue)

Any ideas on what could be causing this?  Apart from this quite irritating issue, it's working fine...

Thanks!

**Comment by dangrossman** [comment]
Probably due to some CSS on your page.
