### ISSUE TITLE
Show End Time selection on Single Date Picker

### ISSUE THREAD

**Issue by shyam06** [dangrossman/daterangepicker#2000]
Hello,

I checking for a solution to display End Time selection option when `singleDatePicker: true ` is added.

Thanks

**Comment by dangrossman** [comment]
What does "end time" mean in a single date picker? It is for picking one moment in time, not a start and end

**Comment by shyam06** [comment]
I want to return the value in below format without showing the right side calendar
`2019-08-10 18:00 - 2019-08-10 23:00`

**Comment by dangrossman** [comment]
You will have to modify the library to meet your needs then. There is no setting that will allow you to choose a range of times with only one calendar.
