### ISSUE TITLE
How  to show only 1 datetime selection ?

### ISSUE THREAD

**Issue by PetroGromovo** [dangrossman/daterangepicker#2004]
Hello,
In laravel 5.8 / Bootstrap v4.1.2 / jquery jQuery v3.3.1 application I use 
daterangepicker (version 3.0.3) and is there is a way to show only 1 datetime selection ?

Yes, it is daterangepicker and it is supposed that it has 2 datetime selection, but in case I use some other 
datetime selection plugin it looks different...

Thanks!

**Comment by dangrossman** [comment]
With the `singleDatePicker: true` setting.

http://www.daterangepicker.com/#example3

http://www.daterangepicker.com/#options
