### ISSUE TITLE
Send raw format when locale is used

### ISSUE THREAD

**Issue by jadamec** [dangrossman/daterangepicker#2006]
Hi there,
how can I send the raw format (DD-MM-YYYY) to backend in case of using custom format (e.g. DD.MM.YYYY) by locale, please? Now it sends date in this locale format which I must parse by myself. There could be an option for it maybe. Thanks!

**Comment by dangrossman** [comment]
Add a hidden input to your form to store the "raw format" and populate that input in your callback function.

**Comment by jadamec** [comment]
Not pretty solution in case of 3+ date inputs, but OK. Thanks.

**Comment by dangrossman** [comment]
Whatever you imagine a pretty solution to be, you can code that. The picker provides you with date objects. How you send them to your backend is entirely up to you.
