### ISSUE TITLE
Support two ranges in one date range picker

### ISSUE THREAD

**Issue by havietduc91** [dangrossman/daterangepicker#2008]
Firstly, congrats for the great effort you've put in date range picker!

How we can make date picker with two ranges?
One range for `set time frame` with `yellow color (#FEF2E5)`
and two range for `compare time frame` with `green color (#E9F6FE)`

could you please see the below image to know more!

![Screenshot (44)](https://user-images.githubusercontent.com/4966192/63563206-7627f680-c58a-11e9-8f23-35c5770c8c96.png)

Thank you in advance!

**Comment by dangrossman** [comment]
You cannot do that with this library, there is no such feature

**Comment by havietduc91** [comment]
So sad but thank you for a quick response!
