### ISSUE TITLE
How it returns name in request variable for php, laravel request?

### ISSUE THREAD

**Issue by javedbaloch4** [dangrossman/daterangepicker#2012]
Hi,

I am trying to use **Predefined Date Ranges** example.

As it gives us `<div>` instead of input so it doesn't has `name` attribute,
So how can I get startDate and endDate in php request variable?

**Comment by dangrossman** [comment]
Create two hidden inputs to store the two dates, and populate those hidden inputs in your callback function. There's an example callback function in the Predefined Date Ranges example.
