### ISSUE TITLE
apply.daterangepicker event dont working after ajax call

### ISSUE THREAD

**Issue by chicosilva** [dangrossman/daterangepicker#2016]
$('.datepicker-acoes-avaliacoes').on('apply.daterangepicker',  function(ev, picker) {
    
    $(this).val(picker.startDate.format('DD/MM/YYYY'))
    $(this).closest('form').submit()

})

After call ajax, a buttton <a class="'datepicker-acoes-avaliacoes"></a> append in a div. Clicking this button, apply.daterangepicker dont working

**Comment by dangrossman** [comment]
Ajax calls do not have any effect on the event listener. The code you've shared is not the problem, and whatever the problem is (likely you creating or re-creating the picker after registering the event listener?), it's not a bug in the library.
