### ISSUE TITLE
Start date with fix time..!

### ISSUE THREAD

**Issue by designinsist** [dangrossman/daterangepicker#2019]
I am using this "startDate: moment().startOf('hour'),"
I was wondering to fix moment() with fix start time.

12/09/2019 09:00:00 AM
So start date and end date with fix start time and end time.

   startDate: moment().startOf('hour'),                                                
 endDate: moment().startOf('hour').add(8, 'hour') (This statement work fine just need to fix start time)
Any idea how  to do that  or it is possible or not ?

**Comment by dangrossman** [comment]
Use the date picker solely for the user to choose a date. Add the "fix time" to that date in your own code (callback function or server-side), when you use the date the user picked. You don't need the UI widget to worry about that.

**Comment by designinsist** [comment]
what about using UI widget ?
