### ISSUE TITLE
Locale format setting is not applied to date range displayed at bottom.

### ISSUE THREAD

**Issue by ranjan-malav** [dangrossman/daterangepicker#2020]
Date range text near the cancel button is not formatted according to supplied locale format settings. This is a span with the class name `drp-selected`.
Attaching a screenshot for further clarification.
![Screen Shot 2019-09-18 at 10 55 25 AM](https://user-images.githubusercontent.com/19403844/65114084-1f83d000-da03-11e9-8512-cae814d13b2b.png)

**Comment by dangrossman** [comment]
This text is formatted according to supplied locale format settings.

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L508

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L535
