### ISSUE TITLE
When click outside the input the range of date still shows

### ISSUE THREAD

**Issue by jpcmf** [dangrossman/daterangepicker#2021]
This is a angular application with the jquery version of plugin. I've set the type of input to search so I have the native option to clear the input. When I set a range of date and apply the date the result returns correctly. The problem is when I try to clear the date range in the input and then I click outside of the input, the date range returns. 

There is any method to really clear this completly? 

Check the video > https://i.imgur.com/LLs62Qk.mp4

**Comment by dangrossman** [comment]
You can clear it with <code>$('#yourelement').val('');</code>. The picker does not search for empty inputs to fill them in, it just fills in the current selection when it's closed.

**Comment by jpcmf** [comment]
Yes, but it's not working @dangrossman 

```  
ngAfterViewInit(): void {
    const clearDate = this._dateElement.nativeElement;

    clearDate.addEventListener('search', () => {
      this.applyRanger.emit(null);

      const selectorDatePicker = $('input[name="dates"]');
      selectorDatePicker.daterangepicker();
      selectorDatePicker.val('');
    });
  }
```
