### ISSUE TITLE
Custom some elements of locale options

### ISSUE THREAD

**Issue by guillaumecardon** [dangrossman/daterangepicker#2027]
Hi,

I use the locale settings of moment.
So i have the option "locale" to "fr"

```
$('#reservationtime').daterangepicker({
	timePicker: true,
	locale : 'fr',
	timePickerIncrement: 10,
    timePicker24Hour: true
})
```

By default, constructor set "format" to : moment.localeData().longDateFormat('LLL'), but we could wish another format (like moment.localeData().longDateFormat('LLLL') or similar

How combine use of moment language and custom some parts ?

Something like this maybe
```
$('#reservationtime').daterangepicker({
	timePicker: true,
	locale : {
		base : 'fr',
		format : "DD-MM-YYYY HH:ii"
	},
	timePickerIncrement: 10,
    timePicker24Hour: true
})
```

**Comment by dangrossman** [comment]
The `locale` setting is an object not a string, and setting it to one does not change the language. 

Check off "locale (example settings)" at http://www.daterangepicker.com/#config

This is how you would change the format string only:

````
$('#reservationtime').daterangepicker({
  locale: { 
    format: 'DD-MM-YYYY HH:ii'
  }
});
````
