### ISSUE TITLE
How to trigger a reapply on change without opening daterangepicker

### ISSUE THREAD

**Issue by Progressed36** [dangrossman/daterangepicker#2028]
I have a selectbox where i want to trigger an apply.daterangepicker on change of the value. this needs to trigger an apply when running the function.

	function triggerClick() {
		$("#daterangelabel").trigger("apply.daterangepicker");
	}
	$('select.weekend-select').on('change', triggerClick );

i know im doing something wrong... or arent i :)

**Comment by vgab09** [comment]
+1

**Comment by waqas-badar** [comment]
Apologize for commenting on closed issue. 

I achieved by using following line:

$('#date_range').trigger('apply.daterangepicker', $('#date_range').data('daterangepicker'))
