### ISSUE TITLE
Webpack / AMD issues

### ISSUE THREAD

**Issue by curtchan** [dangrossman/daterangepicker#2030]
After few hours of debugging with webpack encore it seems like something is going on WRONG there.

Given i have defined jquery and moment.js, the packer will fall into this part (by default, although it is just my assumption after multiple tests) https://github.com/dangrossman/daterangepicker/blob/3d57f7bd6f7f57dd115b3438353b1e3bfabb301f/daterangepicker.js#L12

adding to webpack config:
```
var config = Encore.getWebpackConfig();

config.module.rules.unshift({
    parser: {
        amd: false,
    }
});

module.exports = config;
```
seems to solve the issue. Without that jquery throws exception that `.daterangepicker` is not a function.

I have no knowledge to tell what is wrong there - but something definitely is. :smile:

**Comment by UseMuse** [comment]
@curtchan 
I import in this way
for main.js 
```js
import 'daterangepicker/daterangepicker.js';
import 'daterangepicker/daterangepicker.css';
import moment from 'moment';
```
for webpack use plagin
```js
    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        moment: 'moment'
    })
```
