### ISSUE TITLE
Enable empty field but validity field not work anymore

### ISSUE THREAD

**Issue by itajackass** [dangrossman/daterangepicker#2032]
I need a input field where I can select a date, or leave empty. If I insert invalid date the plugin need to correct it itself.

I've create a jsfiddle to report the problem:

FIRST INPUT EXAMPLE : This input field version works great, but I can't empty the field If need it. God part is that if I insert a invalid date, the field autocorrect itself!

SECOND INPUT EXAMPLE: In this input field I can empty the field if I need, BUT if i wrote invalid date, the invalid value remain!! I'd like the plugin checks for validity on trigger change!

This is my fiddle:

https://jsfiddle.net/k15vzajd/2/

**Comment by dangrossman** [comment]
You can either edit the library to try to make it work how you like, or do your own form validation on your webpage.
