### ISSUE TITLE
"moment ()" does not update after page load

### ISSUE THREAD

**Issue by ayse-ozer** [dangrossman/daterangepicker#2033]
I set the date of the bit that is written in Input now, but the clock is not updated again after the page is loaded.

**Comment by dangrossman** [comment]
That's right.

**Comment by ayse-ozer** [comment]
@dangrossman  
I used the calendar in the vue js project and I want the time written in the input to be always up to date


now clock 22.44 but
[image](https://user-images.githubusercontent.com/47213189/66600952-6783b600-ebaf-11e9-9b4f-4ead85d0a39d.png)

**Comment by dangrossman** [comment]
I understand. There's no support for that in this library.

**Comment by ayse-ozer** [comment]
@dangrossman 
Is there a live library you can recommend?
