### ISSUE TITLE
another NaN issue....

### ISSUE THREAD

**Issue by xtian312** [dangrossman/daterangepicker#2037]
I'm getting invalid dates all of the sudden. These are the codes I've been using that was working fine, but today, I'm getting invalid dates on my picker.

				$('input[name="industrydates"]').daterangepicker({
					singleDatePicker: true,
					opens: "right",
					autoApply: true,
					locale: {
						format: 'YYYY-MM-DD'
					}					
				});

				$('input[name="perioddates"]').daterangepicker({
					timePicker: true,
					opens: "right",
					autoApply: true,
					locale: {
						format: 'YYY-MM-DD h:mm A'
					}					
				});

Any suggestions on how to fix?

**Comment by dangrossman** [comment]
I got no "NaN" using those two snippets of code. "YYY" as a format token gives you "192019" btw.
