### ISSUE TITLE
Zoom bug in iOS 

### ISSUE THREAD

**Issue by dodyg** [dangrossman/daterangepicker#2043]
Choosing a date makes the whole page "zoom in". 

https://i.postimg.cc/bwZzfLQv/zoom-in.gif

If you see on this video capture, when I click on the date, it zoomed in a bit but then it didn't zoom out to normal page. When I scroll up you can see the carousel navigation arrows no longer visible because it has been pushed to the side.

**Comment by dangrossman** [comment]
I don't own any iDevices and I haven't written any iDevice specific code to zoom anything in or out, so this is not going to be fixed unless you're interested in doing it.

**Comment by dodyg** [comment]
OK that's a starting point. 

It happens to the examples here as well https://www.daterangepicker.com/#examples.

Let me do more tests - iOS Safari is really becoming a problem.

**Comment by dodyg** [comment]
It could be related to the iPhone input text zooming https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone/46254706#46254706. I will test this.

**Comment by dodyg** [comment]
```<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">```

This is the solution.  It will prevent the iPhone zoom.
