### ISSUE TITLE
How to add tooltip "text" on hovering over dates in calendar

### ISSUE THREAD

**Issue by akshayguru** [dangrossman/daterangepicker#2045]
I tried using hoverdate but it seems it does not work.
Can somebody help
A bit urgent

**Comment by akshayguru** [comment]
Any idea why this has been closed without any comments.
Does daterangepicker support displaying tooltip ?

Please advise

**Comment by tylercaceres** [comment]
Any update? Thanks in advance.

**Comment by dangrossman** [comment]
There's not going to be an update on a closed issue asking how to add a feature this library doesn't have.
