### ISSUE TITLE
Does daterangepicker support adding tooltip/hover text

### ISSUE THREAD

**Issue by akshayguru** [dangrossman/daterangepicker#2046]
Need to show tooltipwhen user hovers on  dates .
Something like showing prices or any similar text that can be customized.

Something like this one :

```
var datepicker = $('input[name="date"]').data('datepicker'),
    element = datepicker.picker;

element.on('mouseover', 'td.day', function(e) {
  var day = parseInt($(this).html(), 10);
});
```

How to implement it in daterangepicker.

Does daterangepicker support this?

**Comment by dangrossman** [comment]
There is no feature like that.

**Comment by tylercaceres** [comment]
@akshayguru did you end up figuring a way?

**Comment by Slizzygod** [comment]
@akshayguru did you end up figuring a way? x2
