### ISSUE TITLE
Update <input> element on date selection

### ISSUE THREAD

**Issue by aljosa-m** [dangrossman/daterangepicker#2047]
How do I automatically update the value of the <input> element as soon as I select the date, before clicking `apply` button?

**Comment by UseMuse** [comment]
@aljosa-m , this happens automatically, most likely you do not have format matching, try to register the format you use explicitly in locale
```js
  $ ('input [name = "daterange"]'). daterangepicker ({
  ...
  "locale": {
         "format": "DD.MM.YYYY HH: mm: ss"
}
...
   }, function (start, end, label) {
     console.log ("A new date selection was made:" + start.format ('YYYY-MM-DD') + 'to' + end.format ('YYYY-MM-DD'));
   });
```
