### ISSUE TITLE
Need to add custom css class for specific date in daterangepicker

### ISSUE THREAD

**Issue by akshayguru** [dangrossman/daterangepicker#2052]
I need to add custom css class for specific date so as to show different colour font for that date only whenevr the calendar is opened.
I tried using beforeshowday like below but it is not working

`beforeShowDay: function(date) {
console.log("akshay");
var mdates = {
'11/05/2020': 'some description'
};   

var search = date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();
console.log("mdatesmatched"+search);
if (search in mdates) {
console.log("mdatesmatched");
return [true, 'highlight', (mdates[search] || '')];
}

return [false, '', ''];
},   `

**Comment by dangrossman** [comment]
Are you sure you've opened this issue on the right library? There is no `beforeShowDay` setting in this one.

**Comment by akshayguru** [comment]
Ok I also tried isInvalidDate but not working.
Is there any way to achieve custom css class for specific date in daterangepicker

**Comment by dangrossman** [comment]
> isCustomDate: (function) A function that is passed each date in the two calendars before they are displayed, and may return a string or array of CSS class names to apply to that date's calendar cell.

http://www.daterangepicker.com/#options

**Comment by akshayguru** [comment]
ok thanks i will have a look and if any issues will ping you

Thanks

**Comment by akshayguru** [comment]
Can  you also share some link using this function isCustomDate.
I just need sample example on how it is being used.

**Comment by dangrossman** [comment]
Something like this

````
$('#element').daterangepicker({
  isCustomDate: function(date) {
    if (date.format('MM/DD/YYYY') == '11/05/2020')
      return 'special';
    return false;
  }
});
````
