### ISSUE TITLE
Change hour on end date when hour on start date has been changed

### ISSUE THREAD

**Issue by wilecoyte78** [dangrossman/daterangepicker#2054]
I would like to be able to change the hour on the end date when the start date hour has been changed using the drop down selector. Something like this:

		$('#time_range').daterangepicker({
			timePicker : true,
			timePicker24Hour : false,
			timePickerIncrement : 1,
			timePickerSeconds : false,
			startDate: moment().startOf('hour'),
			endDate: moment().startOf('hour').add(1, 'hour'),
			autoApply: true,
			autoUpdateInput: true,
			cancelButtonClasses: 'btn btn-secondary',
			locale : {
				format : 'hh:mm A'
			}
		}).on('show.daterangepicker', function(ev, picker) {
			picker.container.find('.calendar-table').hide();
		}).on('changeStartTime.daterangepicker',function(ev, picker){
			$('#time_range').data('daterangepicker').setEndDate(moment( picker.startDate ).startOf('hour').add(1, 'hour'));
		});

**Comment by dangrossman** [comment]
It's open source code, you can add whatever features you want to your copy.
