### ISSUE TITLE
Time dropdowns in picker do not get the time portion of the date set

### ISSUE THREAD

**Issue by landwire** [dangrossman/daterangepicker#2055]
I am trying to set the time portion like so:
```
$input.data('daterangepicker').setStartDate('24/03/2018 09:30');
$input.data('daterangepicker').setStartDate('27/03/2018 9:30');
$input.data('daterangepicker').setStartDate('29/03/2018 13:30');
```

The date gets set properly, but the time stays at 00:00

Any ideas what I am doing wrong or why this is not working?

**Comment by dangrossman** [comment]
The default date format used for parsing and displaying dates is "MM/DD/YYYY". You'll have to set your own format string that matches what you're passing in and what you want shown. 

````
$('#element').daterangepicker({
  locale: { 
    format: 'MM/DD/YYYY H:mm'
  }
});
````

**Comment by landwire** [comment]
Hi Dan,
Thanks so much for the quick reply!
It works now as expected.
