### ISSUE TITLE
How to add text or html inside of date cell?

### ISSUE THREAD

**Issue by mekela** [dangrossman/daterangepicker#2056]
I would need to add prices inside of booking calendar but I can't find the solution how to do it: 
![image](https://user-images.githubusercontent.com/9112709/70338656-ff231f00-1855-11ea-8ee4-20373f24d797.png)

**Comment by dangrossman** [comment]
The `renderCalendar` function contains the code that generates the HTML for each calendar in the picker. That's where you'd start adding your own code to make this.

https://github.com/dangrossman/daterangepicker/blob/master/daterangepicker.js#L619
