### ISSUE TITLE
DateRagePicker Automatically opens the date range selection filter

### ISSUE THREAD

**Issue by UsamaSajid** [dangrossman/daterangepicker#2060]
![Screenshot_93](https://user-images.githubusercontent.com/41789210/72608813-62b86600-3945-11ea-9b96-e95814f565a5.png)

` modal.find('.start_date').daterangepicker({

   timePicker: true,
                callback: function (startDate, endDate, period) {
                    $(this).val(startDate.format('DD/MM/YYYY') + ' – ' + endDate.format('DD/MM/YYYY'));
                },
                locale: {
                    format: 'MM/DD/YYYY'
                },
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                }
            });`

above is my javascript code 

as you can see in picture filter automatically pop up when open the model

**Comment by dangrossman** [comment]
Looks like something in your modal library maybe transfers focus to the input? I don't know. I can't help.
