### ISSUE TITLE
Transparent days when using Bootswatch: Darkly

### ISSUE THREAD

**Issue by aaronhudon** [dangrossman/daterangepicker#2061]
Using version v3.14.1 with Bootswatch Darkly v4.4.1 (https://bootswatch.com/darkly/) days that are not selected within the month are invisible.

![image](https://user-images.githubusercontent.com/4406811/73113159-1a5df280-3ec7-11ea-969b-6d1b1ce71aa4.png)

**Comment by dangrossman** [comment]
I do not advertise compatibility with arbitrary stylesheets anywhere. This isn't something I need to be informed of. Thank you.

**Comment by ceejayoz** [comment]
Since I've run into this just now, I'd note that the fix is quite simple, @aaronhudon:

```
.daterangepicker {
    color: #000;
}
```
