### ISSUE TITLE
Option to stop disabling months in dropdowns when using minDate/maxDate

### ISSUE THREAD

**Issue by RudeySH** [dangrossman/daterangepicker#2062]
My date range picker only allows past dates, so I'm using `maxDate: moment()`. However, this disables all months after the current month:

![image](https://user-images.githubusercontent.com/3918757/73284847-73929280-41f5-11ea-84fe-405256330d9a.png)

All months except January are disabled, because it is currently January.

If I want to use the dropdowns to navigate to a past month, I first have to select a different year (e.g. 2019) before I can select the month. This is bad UX.

I would like to see an option to disable this behavior. Right now, I'm forced to stop using `maxDate`.

---

For what it's worth, I tried hacking my way around this issue, but I couldn't get it to work. Here is my attempt so far:

```js
// override renderCalendar
var renderCalendar = window.daterangepicker.prototype.renderCalendar;

window.daterangepicker.prototype.renderCalendar = function () {
    // disable minDate/maxDate
    var minDate = this.minDate;
    var maxDate = this.maxDate;
    this.minDate = this.maxDate = false;

    // call base renderCalendar
    renderCalendar.apply(this, arguments);

    // restore minDate/maxDate
    this.minDate = minDate;
    this.maxDate = maxDate;
};
```

The `renderCalendar` function normally prevents selecting a month past `maxDate` (or prior to `minDate`). My hack tries to prevent this by disabling the values of `minDate` and `maxDate`. But it doesn't work, couldn't figure out why.

This is a terrible hack anyway, because this also disables any visual indicator of dates that are unselectable.

**Comment by dangrossman** [comment]
I do not actively develop new features/improvements for this library, so just closing the issue so you're aware of that. If you want to improve this behavior it's on you to do so.

**Comment by patel33hardik** [comment]
step: 1: search using `var monthHtml = '<select class="monthselect">';` into daterangepicker.js
step: 2: remove if condition into month's for loop. or simply replace for loop with the following one.
step: 3: its done. :)  👍 💯 
```
var monthHtml = '<select class="monthselect">';
for (var m = 0; m < 12; m++) {
    monthHtml += "<option value='" + m + "'" +
        (m === currentMonth ? " selected='selected'" : "") +
        ">" + this.locale.monthNames[m] + "</option>";
}
monthHtml += "</select>";
```
