### ISSUE TITLE
 Month being exchanged for day in rangepicker

### ISSUE THREAD

**Issue by abisael** [dangrossman/daterangepicker#2064]
When the day of the selected date is less than 13 the plugin is interpreting value as month
ex:
1 - 12/01/2020
2- 13/01/2020
Returns:
1 - 2020-12-01 
2 - 2020-01-13

**Comment by dangrossman** [comment]
Because the default date format is MM/DD/YYYY. Change it to match the format you're providing instead, either by setting the locale for moment.js on your webpage, or through the options for your date picker:

````
$('#element').daterangepicker({
  locale: {
    format: 'DD/MM/YYYY'
  }
});
````
