### ISSUE TITLE
How to set timePicker limit?

### ISSUE THREAD

**Issue by faizananwerali** [dangrossman/daterangepicker#2065]
How to set timePicker limit? I have singleDatePicker. how can limits its timePicker limit from 07:00am to 08:00pm?

    $('#demo').daterangepicker({
        "singleDatePicker": true,
        "timePicker": true,
        "timePicker24Hour": false,
        "timePickerSeconds": true,
        "autoApply": true,
        "startDate": "02/18/2020",
    }, function(start, end, label) {
      console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
    });

**Comment by dangrossman** [comment]
There is no setting for that, you would have to code it yourself.
