### ISSUE TITLE
singleDatePicker + disabled autoApply = no buttons

### ISSUE THREAD

**Issue by thomasdv** [dangrossman/daterangepicker#2068]
Using the following combination of settings should display buttons under the calendar.

```
singleDatePicker: true,
autoApply: false
```

But it still behaves as autoApply was set to true, not showing buttons, so there is no way for the user to clear the value.

Is this a bug?

**Comment by dangrossman** [comment]
No, this is not a bug. "Clear the value" is not something this library really supports (there's always a date selected).

**Comment by shalin007** [comment]
Is there any way to clear the input? I mean when I clear the input box it still auto-fills the date.
