### ISSUE TITLE
event on click on .prev or .next

### ISSUE THREAD

**Issue by jbajou** [dangrossman/daterangepicker#2076]
Hello,

I'm trying to register to an event when the user changes month to update invalidDates after an ajax call (in order to request them only for the displayed period, and not for infinity) by using .prev or .next "buttons".

Is there anything like that ? Don't seem to find this in the docs, yet it sounds like a basic functionality.

I don't seem to catch any event at all...

Thank in advance

**Comment by dangrossman** [comment]
There's nothing like that and you're probably not catching an event because the calendar HTML is re-created each time the month changes.
