### ISSUE TITLE
Manual edit is not allowing when daterangepicker is  implemented in a popup window

### ISSUE THREAD

**Issue by sajith-experion** [dangrossman/daterangepicker#2077]
Implemented a date range picker using daterangepicker.js  version- 2.1.18, In normal web page it allows manual editing of date range , but in  popup page manual editing is not allowing.

**Comment by expSajith** [comment]
![daterange](https://user-images.githubusercontent.com/23092943/77300574-473a5480-6d14-11ea-9be6-cba7f8cdb394.PNG)

**Comment by dangrossman** [comment]
I'm not going to try to troubleshoot a 3+ year old version of the library, sorry
