### ISSUE TITLE
Question: Date field input is removed for date range picker?

### ISSUE THREAD

**Issue by pragatheeswaranshf** [dangrossman/daterangepicker#2078]
I could see that the date field inputs are removed from the date range picker in the latest version. Is there any config to enable that or is it permanently discontinued? Is there any specific reason to remove those input fields altogether?

![Date-range-picket](https://user-images.githubusercontent.com/46960095/78369690-3bd40c80-75e3-11ea-99f4-77b33d8ae746.png)

**Comment by dangrossman** [comment]
They were removed 3 years ago. There is not an option to re-add them. They were the source of too many bugs.
