### ISSUE TITLE
[Feature Request] Set multiple disabled dates

### ISSUE THREAD

**Issue by timint** [dangrossman/daterangepicker#2081]
First I would like to say great work!

I am missing a feature to set multiple disabled dates.

Maybe jQuery Date Range Picker can inspire you?
https://longbill.github.io/jquery-date-range-picker/

> beforeShowDay (Function)
> 	A function that takes a date as a parameter and must return an array with:
> 	[0]: true/false indicating whether or not this date is selectable
> 	[1]: a CSS class name to add to the date's cell or "" for the default presentation
> 	[2]: an optional popup tooltip for this date
> 	The function is called for each day in the datepicker before it is displayed.

**Comment by dangrossman** [comment]
It has this feature, it is the isInvalidDate option.

**Comment by timint** [comment]
Wohoo! I worked my way from the top to the bottom several times. And somehow I missed this.
Super thanks! :)
