### ISSUE TITLE
autoApply

### ISSUE THREAD

**Issue by GamerSK** [dangrossman/daterangepicker#2082]
Hi,
I found bug. When i have
timePicker: true and autoApply: true, autoApply do not work.
https://ibb.co/n8MdqBK

**Comment by dangrossman** [comment]
That is intended. If you have the time picker enabled, the user has to make up to 8 selections to indicate the dates and times they want selected, and there is no way to know when they have finished "automatically".

**Comment by erperejildo** [comment]
@dangrossman I only have this:
```
$('input[name="daterange"]').daterangepicker({
        autoApply: true
      }
```

And it doesn't work for me either:
<img width="671" alt="Screenshot 2020-07-24 at 10 51 41" src="https://user-images.githubusercontent.com/5629919/88375330-adef7d80-cd9b-11ea-85a1-e426f93156b4.png">

**Comment by dangrossman** [comment]
@erperejildo  That screenshot is of a 3-8 year old copy of this library with a different set of features and options. It may not have had a option called autoApply, I can't remember.

**Comment by erperejildo** [comment]
> @erperejildo That screenshot is of a 5-8 year old copy of this library with a different set of features and options. It may not have had an option called autoApply, I can't remember.

I think it's updated:
<img width="753" alt="Screenshot 2020-07-24 at 10 59 11" src="https://user-images.githubusercontent.com/5629919/88375922-bbf1ce00-cd9c-11ea-8bc7-5f97cecd2861.png">

**Comment by dangrossman** [comment]
The layout hasn't looked like that with the "from" and "to" boxes on the side since version 1.

**Comment by erperejildo** [comment]
thanks for the quick response. I've been looking into my company app and apparently someone installed this library many years ago already and as you mentioned it wasn't updated.
Sorry for the confusion and thanks for pointing me out

**Comment by erperejildo** [comment]
@dangrossman I completely removed the old version and also updated moment.js to last one. It's working now but sometimes I guess an issue related with `this.startDate=O()`:
<img width="499" alt="Screenshot 2020-07-24 at 11 47 58" src="https://user-images.githubusercontent.com/5629919/88379589-8ac8cc00-cda3-11ea-9659-e470110b1b24.png">

Is this something you have seen before? If not don't worry, it should be related to other deprecated library maybe
