### ISSUE TITLE
package weight is more than 300 kB

### ISSUE THREAD

**Issue by Grawl** [dangrossman/daterangepicker#2084]
https://bundlephobia.com/result?p=daterangepicker@3.0.5

```
BUNDLE SIZE 
348.5 kB — MINIFIED
102.5 kB — MINIFIED + GZIPPED

DOWNLOAD TIME
3.42s — 2G EDGE
2.05s — EMERGING 3G
```

Moment.js is 66.3% of package size #1582

jQuery is 26.3% of package size. We can replace it with something smaller, like Lodash

[`size-limit`](https://github.com/ai/size-limit) integration will help in this issue

**Comment by dangrossman** [comment]
No

**Comment by Grawl** [comment]
okay then

**Comment by Grawl** [comment]
maybe you will reference this in readme? something like http://unmaintained.tech/
