### ISSUE TITLE
Adjust the size of the calendar to show the Year Dropdown in Full

### ISSUE THREAD

**Issue by parminderjit-s** [dangrossman/daterangepicker#2086]
Hi, I am having an issue to display the dropdown menu for the year in full. Often, only the first two digits are shown instead of the complete year.
![calendaryear](https://user-images.githubusercontent.com/58060832/80934387-87ecb980-8dfa-11ea-8e0a-fe8f12a2d5d9.jpg)

**Comment by dangrossman** [comment]
Edit your stylesheet. Looks like the <select>s have a lot of padding. Perhaps reduce it some.

**Comment by parminderjit-s** [comment]
Hi, I dont think the stylesheet is causing this. I am using a Limitless template where daterangepicker is used, even on the template the year is not displayed in full.

**Comment by dangrossman** [comment]
A stylesheet causes everything. A stylesheet determines how every pixel in that screenshot appears. And with only the default stylesheet, it doesn't appear like that. Check out the year dropdown in the demo site: http://www.daterangepicker.com/#example3
