### ISSUE TITLE
Change the Default Behavior of Date Range Picker when user click on any Calendar Date

### ISSUE THREAD

**Issue by amitprajapati2298** [dangrossman/daterangepicker#2087]
Hi,
I want to some customization on Date Range Picker and details for the same are given below:

**Following is the default behavior of Date Range Picker:**
If a Date Range is already select and he wants to change it then previous selected Date Range is clear and new Date Range is applied

**I require the following customization:**
Let's consider I have the following Date Range selected and If I click before the selected start date then, only start date should be updated & it should not clear entire Date Range.
And If I click before the selected end date then, only the end date should be updated & it should not clear the entire Date Range.

**Selected Date Range**
![image](https://user-images.githubusercontent.com/30806146/81040456-07e15500-8ec9-11ea-8974-2491b04f0d0b.png)

**After clicking on any date**
![Screenshot_21](https://user-images.githubusercontent.com/30806146/81040467-0fa0f980-8ec9-11ea-9ad1-005680b12112.png)

**Comment by dangrossman** [comment]
You are free to make that customization. It's open source code with an extremely permissive license. There are no new features being developed by anyone here however. I shared this 8 years ago. Best luck with your work.

**Comment by amitprajapati2298** [comment]
Can you please help me how can I achieve my customization

**Comment by dangrossman** [comment]
No, sorry
