### ISSUE TITLE
How to initialize the date range with start/end times but not show in textbox

### ISSUE THREAD

**Issue by aaronhudon** [dangrossman/daterangepicker#2089]
Is there a way to initialize the start/end dates of the control with a *time*, but not have the time shown in the textbox portion of the control?

When I initialize the control with a start/end date, and those dates have times, they are not respected in the "time picker" widgets.  However when I include the locale format, they are.
E.g. {
   "locale": {
         format: 'MM/DD/YYYY HH:mm'
    }
}

Unfortunately, this makes the control show the time in the textbox control.

**Comment by dangrossman** [comment]
Yes. Set `autoUpdateInput: false` so that nothing is put in the text box, and populate it with just the dates yourself, similar to this example: http://www.daterangepicker.com/#example5
