### ISSUE TITLE
Year in the dropdown column only shows 5 entries at a time

### ISSUE THREAD

**Issue by parminderjit-s** [dangrossman/daterangepicker#2094]
Hi, this is the code I use :
`$('.daterange-single-startYear').daterangepicker({ 
	        singleDatePicker: true,
	        minDate:new Date(),
	        showDropdowns: true,
	        minYear: 2020,
	    });`
 
The minimum year was set to 2020 and I find it odd that the maximum year I can see is up to 2025. If I select for example : 2021 or any year, it adds an additional 5 years to the dropdown. What I want to achieve is that the dropdown is able to display at least a 10 year period in the dropdown (2020-2030). I have tried adding maxYear but that did not solve the issue either. 
![date](https://user-images.githubusercontent.com/58060832/82240231-a3b09d80-996c-11ea-921f-f61ea6706404.jpg)

**Comment by dangrossman** [comment]
I cannot reproduce this using your settings. 
![ss](https://user-images.githubusercontent.com/407706/82247737-e9417c00-9914-11ea-8bef-5cd334e5d3bb.png)

**Comment by parminderjit-s** [comment]
@dangrossman  What were the settings you used to achieve that?

**Comment by dangrossman** [comment]
Your settings
