### ISSUE TITLE
picker is not redrawn on singleDatePicker change

### ISSUE THREAD

**Issue by Yannik** [dangrossman/daterangepicker#2099]
In my application, the user needs to be able to switch between picking a single date and a date range dynamically.

I'm trying to achieve this by setting `singleDatePicker` to `true`/`false`. 

Generally this works, i.e. the user is correctly able to select a single date/date-ring.

Unfortunately, there's one short-coming: The calendar is not redrawn when doing this, which means that only a single calendar is visible when switching from single date to date range (which breaks selecting a range over multiple months), and vice versa.

It'd be great if there was a 'redraw' method for this, or, if this would be done automatically.

**Comment by dangrossman** [comment]
How are you changing the setting? The only supported way is to call `$.daterangepicker(options)` again with the new options, which would create a new picker with the correct appearance.

**Comment by Yannik** [comment]
I'm changing it using `data('daterangepicker').singleDatePicker = true/false`. 

Is it possible to get all current options of a picker so I can use your recommended `$.daterangepicker(options)` with the correct settings apart from `singleDatePicker`?

**Comment by dangrossman** [comment]
Put all your options in a variable so you can reuse it when you flip the singleDatePicker property of it. This would be less code than trying to read out all the options...

**Comment by Yannik** [comment]
@dangrossman There are a few other options like `minDate` I need to dynamically change (based on whether the user has chosen an `express` option).
With your suggestion I would need to duplicate setting these options (setting them both in the options object and in the actual (current) picker), which I'd like to avoid.

Is there no option to access an object of all current options or redraw another way?

**Comment by dangrossman** [comment]
You can either do it the way it's coded now, or you can rewrite the code to work how you'd prefer. The beauty of free open source software.

**Comment by Yannik** [comment]
@dangrossman Would you accept a PR which allows for this?

**Comment by dangrossman** [comment]
Probably not. There's already a method to redraw the picker to reflect new settings, as described above. I don't want to maintain new code just for a single person. TY for the thought though.
