### ISSUE TITLE
Instructions for working with webpack

### ISSUE THREAD

**Issue by RailsCod3rFuture** [dangrossman/daterangepicker#2102]
I installed the npm package for daterangepicker, but webpack does not recognize the require("daterangepicker") statement after install. I still receive **TypeError: $(...).daterangepicker is not a function at HTMLDocument.** What should I do to set this up correctly?

**Comment by dangrossman** [comment]
I cannot help you with this, as I've never used Webpack. This library predates its existence.

**Comment by mcritchlow** [comment]
@RailsCod3rFuture - fwiw, I had this plugin working fine in a previous version, and am now getting the error you mention upon upgrade. That said, I haven't isolated the error to this plugin.

At the moment, with this diff, I get your error:

![image](https://user-images.githubusercontent.com/67506/83447029-9c759f00-a404-11ea-8eb8-9c1602abcc35.png)

If it's at all helpful, here's how I set things up for this plugin:

environment.js:

```
const { environment } = require('@rails/webpacker')

const webpack = require('webpack')

// Enable the default config
environment.splitChunks()

environment.plugins.prepend(
  'Provide', new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    Popper: ['popper.js', 'default']
  })
)

const MomentLocalesPlugin = require('moment-locales-webpack-plugin')
module.exports = {
    plugins: [
        // To strip all locales except “en”
        new MomentLocalesPlugin(),
    ],
}

module.exports = environment
```

In a custom js file that's only used on the view I need this functionality:

```
/* eslint no-console:0 */
import 'src/globals'
import 'popper.js'
import 'bootstrap'
import moment from 'moment'
moment.locale('en')

import 'bootstrap-daterangepicker'

jQuery(document).ready(function(){
  $('#start_date').daterangepicker({
    singleDatePicker: true,
    startDate: moment().startOf('month'),
    minYear: 2019, //app first deployed in 2019
    maxYear: new Date().getFullYear(),
    showDropdowns: true,
    locale: {
      format: 'YYYY-MM-DD'
    }
  })
  $('#end_date').daterangepicker({
    singleDatePicker: true,
    minYear: 2019, //app first deployed in 2019
    maxYear: new Date().getFullYear(),
    showDropdowns: true,
    locale: {
      format: 'YYYY-MM-DD'
    }
  })
})
```

My `src/globals` is just:
```
/* eslint no-console:0 */

// global imports for all packs
import 'core-js/stable'
import 'regenerator-runtime/runtime'
import Rails from '@rails/ujs'

import 'css/application'

Rails.start()
```

**Comment by felipefava** [comment]
I'm facing the same issue, with jquery 3.4.1 was working fine, now with jquery 3.5.1 is broke with the error `daterangepicker is not a function`. Any fix or workaround for this issue?

**Comment by dangrossman** [comment]
The documentation site (http://www.daterangepicker.com/) is using jQuery 3.5.1 and daterangepicker.js with no errors or other issues.

**Comment by chetan** [comment]
Figured out what the issue is here. It occurs when you do a fresh install (no existing lock file) and you get different jquery versions in your application vs bundled with `daterangerpicker`:

```
❯ yarn list jquery
├─ daterangepicker@3.1.0
│  └─ jquery@3.5.1
└─ jquery@3.3.1
```

In this scenario, daterangerpicker registers itself with v3.5.1 while your app is using v3.3.1. The fix is to get them both on the same version - either upgrade your app's dependency to match (bump to 3.5.1) or add an exclusion to force daterangerpicker to use your version - 

```
  "resolutions": {
    "daterangepicker/jquery": "3.3.1"
  }
```

**Comment by mcritchlow** [comment]
@chetan - Thanks for this, that was definitely the issue on my end

**Comment by colonelclick** [comment]
@chetan Thanks. Updating my jQuery base version to the latest (currently 3.5.1) fixed the issue with using this in Webpack.
