### ISSUE TITLE
Disable Specific Day(s) of Every Month

### ISSUE THREAD

**Issue by shery089** [dangrossman/daterangepicker#2105]
Hello, 
Thank you so much for this great plugin. I am trying to disable specific day(s) of month. My client's business is not operational on Monday. I want the following effect.

![image](https://user-images.githubusercontent.com/11508556/83923230-40f83800-a79b-11ea-862d-fbfd4f27845f.png)

This is done with jQuery. As soon as click on some date the disable day i.e Monday is active again.
I am trying to find an **option** or **event** but unable to find one. Please can someone help me out?
Thanks!

**Comment by dangrossman** [comment]
```
$('#element').daterangepicker({
  isInvalidDate: function(date) {
    //return true on Mondays
    if (date.day() == 1)
      return true;
    return false;
  }
});
```
