### ISSUE TITLE
Please submit to packagist.org

### ISSUE THREAD

**Issue by MAXiDROME** [dangrossman/daterangepicker#2112]

**Comment by dangrossman** [comment]
This is not a PHP package

**Comment by MAXiDROME** [comment]
There are a lot of javacript packages on packagist. It is just a repository!

**Comment by dangrossman** [comment]
The site's name is "The PHP Package Repository" and their tagline is "It aggregates public PHP packages...". Feel free to submit and maintain a package of your own there if you wish.
