### ISSUE TITLE
Large year range in dropdown not focusing on the selected year

### ISSUE THREAD

**Issue by prachijainfound** [dangrossman/daterangepicker#2114]
I have values in year dropdown from 1900 to current year. If my selected date is 05/31/2018 as start date. The year dropdown always show values from 1900 on open. I need to scroll down a lot to reach on the selected year.

**Comment by prachijainfound** [comment]
Can anyone please help.

**Comment by dangrossman** [comment]
Can you share the code you're using to reproduce this?

**Comment by prachijainfound** [comment]
i did the basic settings of DateRangePicker as below :
this.datePicker = {
locale: {
         daysOfWeek: ["S", "M", "T", "W", "T", "F", "S"],
         format: 'DD-MMM-YYYY'
},
showDropdowns: true,
singleDatePicker: false,
getDateRangeForCode: (code: any) => {},
startDate: this.$scope.dateSelected,
endDate: this.$scope.dateSelected,
showDefaultDate: false,
linkedCalendars: false,
checkInvalidDate: true
};

**Comment by dangrossman** [comment]
Two things:

1. Several of those options do not exist in this library, so you may be using a different library or a fork

2. I could not reproduce your problem with these options. The picker opened at the year 2018 not 1900. The year 1900 isn't even an option in the dropdown. 

![ss](https://user-images.githubusercontent.com/407706/85208946-2dec7880-b302-11ea-880c-2d589b829930.png)
