### ISSUE TITLE
Days of week and date don't line up

### ISSUE THREAD

**Issue by yannickmcosta** [dangrossman/daterangepicker#2116]
![image](https://user-images.githubusercontent.com/2808874/86020275-9e407b80-ba1f-11ea-9d76-3c7d4937e018.png)

Seem to be having an issue with the days of the week at the top of the custom selection calendar not lining up with the actual day of the week. In this example, today is Monday 29th June and selected is the Saturday, which of course is incorrect :)

Have tried removing a multitude of options to no avail, and have also changed the `firstDay` variable but this makes no difference either.

Options Listed below for info:

```
$('#daterange').daterangepicker({
	"minYear": 2012,
	"maxYear": 2020,
	"opens": "left",
	"autoApply": true,
	"alwaysShowCalendars": true,
	"maxSpan": {
		"days": 30
	},
	ranges: {
		'Today': [moment(), moment()],
		'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
		'Last 7 Days': [moment().subtract(6, 'days'), moment()],
		'Last 30 Days': [moment().subtract(29, 'days'), moment()],
		'This Month': [moment().startOf('month'), moment().endOf('month')],
		'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
	},
	"locale": {
		"format": "DD/MM/YYYY",
		"separator": " - ",
		"applyLabel": "Apply",
		"cancelLabel": "Cancel",
		"fromLabel": "From",
		"toLabel": "To",
		"customRangeLabel": "Custom",
		"weekLabel": "W",
		"daysOfWeek": [
			"Mo",
			"Tu",
			"We",
			"Th",
			"Fr",
			"Sa",
			"Su"
		],
		"monthNames": [
			"January",
			"February",
			"March",
			"April",
			"May",
			"June",
			"July",
			"August",
			"September",
			"October",
			"November",
			"December"
		],
		"firstDay": 0,
	},
	"startDate": "01/01/2020",
	"endDate": "01/02/2020"
}, function(start, end, label) {
  console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
});
```

**Comment by dangrossman** [comment]
Your custom "daysOfWeek" labels need to start with Sunday.

**Comment by yannickmcosta** [comment]
Hi, thanks for the response, but that hasn't fixed it and has in fact made it worse.

I tried to shift them about but nothing seemed to make the dates line up. Plus, we count Monday as the start of the week, not the Sunday so want that reflected

![Screenshot 2020-07-06 at 14 08 14](https://user-images.githubusercontent.com/2808874/86596496-309dcd80-bf92-11ea-8e48-d5358ca08944.png)
![Screenshot 2020-07-06 at 14 08 28](https://user-images.githubusercontent.com/2808874/86596501-31cefa80-bf92-11ea-9a4a-f4e40c8ee356.png)
