### ISSUE TITLE
how to use this in Vue js

### ISSUE THREAD

**Issue by AXWELL911** [dangrossman/daterangepicker#2117]
how to use this in Vue js and how to get selected date range

**Comment by devsuitup** [comment]
Like this https://www.npmjs.com/package/vue2-daterange-picker

**Comment by AXWELL911** [comment]
@devsuitup can provide any proper example pls @dangrossman

**Comment by dangrossman** [comment]
I do not know anything about Vue.js nor do I maintain the Vue.js port.
