### ISSUE TITLE
I want to use two inputs for the date range picker.  when i select the start date i want the focus to move to the other input. How do i achieve that? I need urgent help. 

### ISSUE THREAD

**Issue by sumannunia** [dangrossman/daterangepicker#2119]
![image](https://user-images.githubusercontent.com/51792560/86559412-85811a00-bf79-11ea-8442-03a9f31df45e.png)

**Comment by dangrossman** [comment]
That's something you'll need to code on your own. It is not a feature of this library.

**Comment by sumannunia** [comment]
i want a clue on how to trigger the select on one of the calender and move to the other input.
