### ISSUE TITLE
default ranges are not displaying when "LAST MONTH" range is enabled

### ISSUE THREAD

**Issue by radhaviki10** [dangrossman/daterangepicker#2122]
default ranges are not displaying when "LAST MONTH" range is enabled

This is my code to render daterangepicker component.
`$(function () {

            var start = moment().subtract(1, 'month').startOf('month');
            var end = moment().subtract(1, 'month').endOf('month');
            let startDate;
            let endDate;

            function cb(start, end) {

                    let label = $('#reportrange').data('daterangepicker').chosenLabel

                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));

            }

            $('#reportrange').on('apply.daterangepicker', function (ev, picker) {
                // _this.dateRangePickerApply(ev, picker);
            });
            console.log('reportrange ##########', start, end)
            $('#reportrange').daterangepicker({
                startDate: start,
                endDate: end,
                maxDate: end,
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                    'This Year': [moment().startOf('year'), moment()],
                    'Last 365 Days': [moment().subtract(365, 'days'), moment()]
                }
            }, cb);

            cb(start, end);
        });`

**when I provide the moment value of last month. The UI part renders the ranges that are after LAST MONTH. Please Go through the attached Image and Kindly suggest a Solution.**

![image](https://user-images.githubusercontent.com/68228822/87301361-12eddc80-c52d-11ea-8a0d-213cb79ae7e8.png)

**Comment by dangrossman** [comment]
The predefined ranges that weren't rendered are invalid due to your `maxDate` of June 30th. No date in "last 7 days" is before June 30th for example.

**Comment by radhaviki10** [comment]
Yeah after changing the maxDate to current moment it is working thank you for your comments.
