### ISSUE TITLE
minDate is not updated when datepicker is reinitialized in method call

### ISSUE THREAD

**Issue by radhaviki10** [dangrossman/daterangepicker#2125]
**minDate is not updated when datepicker is reinitialized in method call**

Understood that in daterangepicker component, only way to change minDate programatically by user operation is to reinitialize the picker. I have called the below code from a button click event, but min date is not changing in target daterange picker

Version : "daterangepicker": "3.1.0"
Code given below

`$('#reportrange').daterangepicker({
                singleDatePicker: true,
                timePicker: true,
                timePicker24Hour: true,
                showDropdowns: true,
                minDate: moment(localdatetime),
                locale: {
                    format: 'DD/MM/YYYY HH:mm'
                }
            });`
       

Kindly provide possible solution to update minDate.

**Comment by jasmalmk** [comment]
minDate and maxDate not working when it set dynamically
