### ISSUE TITLE
Unable to set minDate inline

### ISSUE THREAD

**Issue by milan-sahana** [dangrossman/daterangepicker#2126]
When I want to set minDate inline, its not working.
code :
```
<input type="text" name="start_date" class="form-control singledate" value="07/07/2020"  setMinDate="01/01/2020" >
<script>
$('.singledate').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
    });
</script>
```

**Comment by dangrossman** [comment]
There's no code that reads a "setMinDate" tag you made up. Nothing in the documentation suggests it will.

**Comment by milan-sahana** [comment]
> 
> 
> There's no code that reads a "setMinDate" tag you made up. Nothing in the documentation suggests it will.

How can I set minDate inline?
if corrent version there is no option for that, please make this option in future,
