### ISSUE TITLE
Is there any event to capture any single date change in DateRangepicker?

### ISSUE THREAD

**Issue by prachijainfound** [dangrossman/daterangepicker#2129]
I am facing problem in selecting the individual date if it is DateRange picker.
Let suppose I select 01/07/2018 as Start Date and 30/07/2020 as End Date but mistakenly clicked on 29/07/2020.
I need to go alltogether from the scratch.
Is there any way to capture the date selection event occurs from Second Calendar or First Calendar.

Thanks in advance.

**Comment by dangrossman** [comment]
No, there are no additional events for partial selections or which calendar was clicked.
