### ISSUE TITLE
Full month name in format ignores locale monthNames

### ISSUE THREAD

**Issue by loeffe1** [dangrossman/daterangepicker#2130]
I have defined both locale monthNames and a custom format DD. MMMM YYYY and while the locale months names are correctly displayed in the rangepicker, the input will still display the english month names

![drp](https://user-images.githubusercontent.com/42471369/88907922-82680980-d259-11ea-96a0-569a6aaaa6c6.png)

**Comment by dangrossman** [comment]
The "DD. MMMM YYYY" is formatted by the Moment library using whatever locale is set on your webpage

Here's how to change it: https://momentjs.com/docs/#/i18n/

**Comment by loeffe1** [comment]
Thank you
