### ISSUE TITLE
Update UMD template to support ES modules

### ISSUE THREAD

**Issue by mwanji** [dangrossman/daterangepicker#2131]
Within an ES module, `this` is undefined, rather than `window`. This causes `import './daterangepicker.js'` to fail on line 29: https://github.com/dangrossman/daterangepicker/blob/6075b419d6072010accda52080322e1487c4cc7b/daterangepicker.js#L29

The UMD template you're using was updated in September 2017 to detect `window` instead: https://github.com/umdjs/umd/blob/47e725735b854dfd93c1ca6fcebf1e018bd52606/templates/returnExportsGlobal.js#L32

**Comment by dangrossman** [comment]
Feel free to make a fix. I don't use any of this stuff, so I can't test whether I've made the change you wanted.

**Comment by mwanji** [comment]
@dangrossman Thanks for the quick reaction!
