### ISSUE TITLE
Day.js & Scss

### ISSUE THREAD

**Issue by GeoSot** [dangrossman/daterangepicker#2134]
Please make a thought of using as an option the day.js (is smaller) 
And it is really a pity , for all , not to be able to use an scss file with variables

It is the best library i know for time handling, but it need some small push.

**Comment by dangrossman** [comment]
Perhaps consider creating a fork that uses day.js and scss. I will not be doing it. I made this 8 years ago and it does what I need. I do not have time to invest in a rewrite for others' benefit, when I have paid work to be doing, sorry.
