### ISSUE TITLE
short year YY not working as expected

### ISSUE THREAD

**Issue by irvine48** [dangrossman/daterangepicker#2140]
Hi,

I did search through all issue, but can't find any answer for this.

test on version 3.0.1 and 3.1.0

i am looking to format year into short two digit year.

code as below,
```
$('#date').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            autoApply: true,
            locale: {
                format: "DD.MM.YY"
            }
        }, function(start, end, label) {
});
```
for 2013
my input field will result me 20 but not 13 as expected, do this a bug?

YYYY show me 2013 no issue.

**Comment by dangrossman** [comment]
I do not experience this bug using your code. I suspect you have a 4-digit year in your input to start with? It's going to be parsed according to the format string you provided, which means "2013" will become "20".

![ss](https://user-images.githubusercontent.com/407706/89930395-b0920580-dbd8-11ea-8fa4-6980661e7791.png)

**Comment by irvine48** [comment]
yes, my original form input format as 08.11.2013

oh god, thank you so much. save my day. thank!!!
