### ISSUE TITLE
How to disable manual input (force user select from calendar)?

### ISSUE THREAD

**Issue by tohizma** [dangrossman/daterangepicker#2141]
There's no option to disable input field, so user able to enter arbitrary string in input field that generate error on date conversion

We want to force user use and choose from displayed calendar instead

**Comment by dangrossman** [comment]
Don't use a text input, or if you must, make it readonly.

**Comment by DonDiegoAA** [comment]
Making text input readonly is not a good solution when this field need to be required too (required doesn't work with readlonly).
