### ISSUE TITLE
single date picker mode does not call function when current day is selected

### ISSUE THREAD

**Issue by lucaspcamargo** [dangrossman/daterangepicker#2147]
I am using daterangepicker version 3.0.5

When I create the picker on an input with the following settings:

- singleDatePicker: true
- autoUpdateInput: false
- autoApply: true

It pops up immediately, with today's date selected. But when I click it, since the internal date did not change, the callback is not invoked. I need to call it even when the user clicks on today. Is there a way to force this to happen?

**Comment by dangrossman** [comment]
This is as intended. The callback function is triggered by a change in the selected date(s) only. The apply event is fired every time however. Here's some example code: http://www.daterangepicker.com/#example5

**Comment by ptjuanramos** [comment]
```
if (!this.startDate.isSame(this.oldStartDate) || !this.endDate.isSame(this.oldEndDate))
                this.callback(this.startDate.clone(), this.endDate.clone(), this.chosenLabel);
```

But I do not understand that by design it should be intended. Or it should have some kind of flag in order to ignore this validation.

**Comment by dangrossman** [comment]
@ptjuanramos 

Read the comment immediately above yours.

If you want to be notified only when the selection changes, use a callback function. It is only triggered on a new selection.

If you want to be notified even if the same dates are clicked again, use the apply event. It is triggered always.
