### ISSUE TITLE
Unexpected behaviour: minDate and maxDate

### ISSUE THREAD

**Issue by lordplagus02** [dangrossman/daterangepicker#2148]
Given the following configuration, these options seem to break both calendars when choosing date range.
Using latest Bootstrap, jQuery and Moment, given the following configuration:

`$('#range-picker').daterangepicker({
            "showDropdowns": false,
            "autoApply": true,
            "autoUpdateInput": false,
            "linkedCalendars": false,
            "minDate": "01/01/2014",
            "maxDate": moment().format('MM/DD/YYYY')
        }, function() { });`

**Comment by dangrossman** [comment]
I see a normal working date range picker when I use that code, as you wrote it:

![ss](https://user-images.githubusercontent.com/407706/93232577-0f9ee900-f748-11ea-99a1-24c99b33bf90.png)
