### ISSUE TITLE
windown calendar size problem

### ISSUE THREAD

**Issue by alexbrito2020** [dangrossman/daterangepicker#2150]
Hi,
I started use datarangepicker today and when a execute it the window calendar is a little bit short.
Somebody know why this happens.
I download the file from http://www.daterangepicker.com/
So I guess it is not a file problem.

![daterangepicker](https://user-images.githubusercontent.com/61800373/93270677-003f9000-f788-11ea-8ea5-848426b11ff5.PNG)

Thank you for attention.

**Comment by dangrossman** [comment]
Something in your stylesheet has added extra padding to the table cells that make up the calendars, so they no longer fit the given space. You would fix this in your site's stylesheet (.css file).

**Comment by alexbrito2020** [comment]
Just to give a help to somebody who can have the same problem.
Following the tip off the css file, I found that the bootstrap.css has a line tag called ".table-candensed td" that has the property padding which was make the Calender a little bit small.
I am using bootstrap 4.
Thank you for your attention.
