### ISSUE TITLE
Moment.js is now a deprecated library

### ISSUE THREAD

**Issue by yuuu** [dangrossman/daterangepicker#2154]
Moment.js is now a deprecated library, as noted in the following URL.

https://momentjs.com/docs/

Right now, daterangepicker relies on Moment.js, but why not move to another library?

**Comment by dangrossman** [comment]
It is not deprecated, it is "done". 

You should consider the same about this project, which was written 8 years ago, for all the same reasons.

It will not be moving to another date library.
