### ISSUE TITLE
DateRangePicker rendering issue

### ISSUE THREAD

**Issue by pedrogilsantos** [dangrossman/daterangepicker#2160]
Hi , 

I'm trying to implement Daterangepicker within CoreUI template (Bootstrap 4 version) [.](https://coreui.io/demo/3.2.0/)
For some reason when I click to open the calendar, it is not properly rendered and it appears in the left bottom of my page with styles missing.
![image](https://user-images.githubusercontent.com/6074740/96463141-4e7bff00-121e-11eb-8711-1d8d6aa62035.png)

It seems like a css conflict, but I can't detect where is the issue. Does someone add similar issue, or can help me fixing this?

Many thanks

**Comment by dangrossman** [comment]
Looks like perhaps you haven't included the daterangepicker.css file
