### ISSUE TITLE
Stop refreshing Daterangerpicker when we are selecting Dates

### ISSUE THREAD

**Issue by wavehamza** [dangrossman/daterangepicker#2163]
Is there a way to stop refreshing the daterangepicker ? or somehow an event to detect when i click a date (not apply button) ? 

Thanks.

**Comment by blockmonkey** [comment]
Is there an Event that detects when either the Start or End Date is selected?

**Comment by dangrossman** [comment]
No

**Comment by blockmonkey** [comment]
Darn. Seriously love this Date Picker 😀 thx for the quick reply.
