### ISSUE TITLE
disable all mondays and tuesdays in the calendar

### ISSUE THREAD

**Issue by dhruvanand96** [dangrossman/daterangepicker#2167]
will it be possible to disable all the monday's and tuesdays of the month

**Comment by dangrossman** [comment]
```
$('#element').daterangepicker({
  isInvalidDate: function(date) {
    returrn date.day() == 1 || date.day() == 2; //return true on monday and tuesday
  }
});
```

**Comment by dhruvanand96** [comment]
Hi Dan,

Thank so much.

--
Dhruv Anand
https://codingfreaks652730050.wordpress.com/
https://github.com/dhruvanand96

**Comment by dhruvanand96** [comment]
Hi Dan,

thank you so much.
--
Dhruv Anand
https://codingfreaks652730050.wordpress.com/
https://github.com/dhruvanand96
