### ISSUE TITLE
How to open the picker with start date

### ISSUE THREAD

**Issue by polianomartini** [dangrossman/daterangepicker#2168]
I have a start date on a variable. Is it possible to trigger the "show.daterangepicker" event to mark the start date in the picker and when moving the mouse to select only the end date?

I tried it this way:

```javascript
.on("show.daterangepicker", function(ev, picker) {
    let startDate = getVarDateStart();

    picker.setStartDate(startDate);
    picker.setEndDate(null);

    picker.updateView();
})
```

Thus, when opening the calendar, the start date is marked and when dragging the cursor it does not show the selection effect, having to start the start date again.

**Comment by dangrossman** [comment]
There is not a setting for this
