### ISSUE TITLE
How to set minimum days between selected start and end day?

### ISSUE THREAD

**Issue by stojankukrika** [dangrossman/daterangepicker#2169]
Default is 0 days, which means a client can select start and end days to be the same day. Can I somehow define to end the day can be a minimum of one day ahead, for example, client select start day as today and min end day mus be tomorrow or some day before tomorrow?

**Comment by JamoCA** [comment]
I was considering the same thing. I have requirements where the end date must be 7+ (or 30+) days from the start.

**Comment by monaalexandra** [comment]
I have the same challenge. Essentially, we would need a "minSpan" like the "maxSpan" option.

**Comment by freddy-daniel** [comment]
This is required feature

**Comment by sajjadalirixvi** [comment]
any update on this feature?

**Comment by dangrossman** [comment]
This feature does not exist, but you can add it
