### ISSUE TITLE
Minimum range for each month?

### ISSUE THREAD

**Issue by Endless05** [dangrossman/daterangepicker#2178]
How can I choose the minimum selection for each month? For example I'm using this code;

$('.date-picker input').daterangepicker({
"minSpan": {
        "days": 5
    },
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY'
            }
        });

I want this code like this;

$('.date-picker input').daterangepicker({

if(this.month==5){
"minSpan": {
        "days": 5
    },
}
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY'
            }
        });

**Comment by dangrossman** [comment]
There is no feature like that
