### ISSUE TITLE
I have problems for invalidating dates

### ISSUE THREAD

**Issue by Jonas21** [dangrossman/daterangepicker#2181]
I can override specific dates. I am using daterangepicker for a reservation system. The problem is that you can select a date range with invalid dates in between. Can you help me?

<pre><code>
		$('input[name="date-range"]').daterangepicker({
			autoApply: true,
			opens: 'center',
			parentEl: "#modalReservationRequest .modal-body",
			timePicker: true,
			timePicker24Hour: true,
			showDropdowns: true,
			minDate: moment(),
			startDate: moment().add(1, 'day'),
			endDate: moment().add(2, 'day'),
			maxYear: parseInt(moment().format('YYYY')) + 4,
			locale: {
				"format": "YYYY/MM/DD HH:mm",
				"separator": "-",
			},		

			isInvalidDate: function(date){

				var arrayInvalidDates = JSON.parse($('#confirmReservationRequest').attr('attr-data-available-dates-reservation'));
				
				newDateRanges = [];

				$.each(arrayInvalidDates, function( index, value ) {

					var chargeDetails = {
						'start' : moment(value.start),
						'end' : moment(value.end)
					};
					
					newDateRanges.push(chargeDetails);
				});

				return newDateRanges.reduce(function(bool, range) {
					return bool || (date >= range.start && date <= range.end);
				}, false);

			}
			
		});</code></pre>
![image](https://user-images.githubusercontent.com/5990792/110622880-596b0800-819c-11eb-8242-520d58b5feaa.png)

**Comment by dangrossman** [comment]
That is correct. There is no feature in this library that would meet your requirement.

**Comment by Jonas21** [comment]
> That is correct. There is no feature in this library that would meet your requirement.


I can not do anything?
