### ISSUE TITLE
Can you add an event on the right-click and prevent the default behavior

### ISSUE THREAD

**Issue by rezored** [dangrossman/daterangepicker#2186]
Hello, can you add an event on the right-click and prevent the default behavior?
What I need to accomplish is add a custom class to the selected date and get the date from the to right-click so I can store it in an array. The point is that the array that I will get will be an exclude dates array. 
For example - select one month as a period and then exclude several days, those exclude will be added with right-click, and to mark then - add a different style, the event will provide the excluded date so it can be stored and further used as an array.

**Comment by dangrossman** [comment]
You can certainly add that event for yourself. It's open source code.
