### ISSUE TITLE
moment.js now considered legacy and recommend using other libraries

### ISSUE THREAD

**Issue by nvurgaft** [dangrossman/daterangepicker#2191]
moment.js now considered legacy and recommend using other libraries.

https://momentjs.com/docs/#/-project-status/

considering moment is a core dependency, how will that influence this repo ?

**Comment by dangrossman** [comment]
This is also a nearly 10 year old library "built for the previous era of the JavaScript ecosystem" which hasn't gotten new features in years. Moment.js prioritizing stability a year ago changes nothing.
