### ISSUE TITLE
setEndDate called although endDate is set

### ISSUE THREAD

**Issue by coltman21** [dangrossman/daterangepicker#2194]
I just updated our project with your latest version.

We're setting the format to "DD.MM.YYYY HH:mm:ss" and the 'endDate' to today at 23:59:59. Due to using the options `timePicker=true` and `timePickerIncrement=5`, the date will now always be set to tomorrow at 00:00:59.

This happens in the function setEndDate on line 494-495.

Do you might have a quickfix for this?

Best regards
Steven

**Comment by dangrossman** [comment]
The quick fix would probably be to not provide incompatible settings (23:59:59 is not an increment of 5).
