### ISSUE TITLE
range selector / calendar view line separator height sometimes insufficient

### ISSUE THREAD

**Issue by Slos** [dangrossman/daterangepicker#2197]
The light grey vertical line separating the custom range selector section from the calendar view section does not render all the way to the bottom when there is a long list of custom predefined ranges.

![date_picker_issue](https://user-images.githubusercontent.com/9729859/120075759-decace00-c0a2-11eb-91c3-21c7bc870622.png)

**Comment by dangrossman** [comment]
Feel free to improve it and submit a PR, or just fix it in your own stylesheet
