### ISSUE TITLE
Disable alternate week?

### ISSUE THREAD

**Issue by jeetyajnik** [dangrossman/daterangepicker#2198]
I want to disable alternate weeks but I am not sure how to do that. I am passing dates in `isInvalidDate` but I am unable to do it. Is there I can disable whole week at once and increase the date value which I am passing?

```
$('#element').daterangepicker({
  isInvalidDate: function(date) {

    How to know if its an alternate week as there are multiple conditions I am checking inside this.

  }
})
```

**Comment by dangrossman** [comment]
Check the week number of `date`, e.g. using moment's `.week()`. If it's an even number, return true. If it's an odd number, return false. You can check even/odd of a number by checking the remainder of dividing by 2 (num % 2 == 0). This would disable alternating weeks.
