### ISSUE TITLE
Drops: auto does not work logically (in my opinion)

### ISSUE THREAD

**Issue by tuur155** [dangrossman/daterangepicker#2199]
I used the test.html and changed the code in daterangepicker.js so that drops is always auto. When opening the datepicker this is the result: 
![image](https://user-images.githubusercontent.com/48909622/120342114-c56e8f80-c2f7-11eb-8411-f04e88e64055.png)

As you can see the datepicker renders up but you can not view the whole datepicker.

however, when you give the body padding so there is space underneath the datepicker this is the result: 
![image](https://user-images.githubusercontent.com/48909622/120342231-e2a35e00-c2f7-11eb-859f-b469c685d628.png)

This does not seem like the intended behaviour.

**Comment by dangrossman** [comment]
Feel free to improve it and submit a PR if you'd like
