### ISSUE TITLE
Create DateRange with open border

### ISSUE THREAD

**Issue by VaDRo** [dangrossman/daterangepicker#2200]
I'm creating reporting system with this control. I need to give ability for user to select ranges where one of the borders is open. Sometimes user wants to select date range from specified date to the future. Or from the past to specified date. This date ranges could be used for tasks like "Give me all orders till 04-03-2021" or "Give me bills from 11-05-2020". In math terms this date ranges could be described as (-infinity, 04-03-2021] and [11-05-2020, infinity) respectively
Is there any way to create such way of date range selection?

**Comment by dangrossman** [comment]
Probably with separate date pickers for the start and end date, so one can be left empty. That means you don't need a "date range picker" widget.

**Comment by VaDRo** [comment]
But I need ability to select full ranges at the same time...

**Comment by dangrossman** [comment]
You can select a range by picking both a start and end date

![ss](https://user-images.githubusercontent.com/407706/120526650-6ec08e80-c3a7-11eb-9810-3373ef8bfb75.png)
