### ISSUE TITLE
Navigation of unlinked second calendar is not flexible

### ISSUE THREAD

**Issue by sun-tea** [dangrossman/daterangepicker#2201]
When `linkedCalendars` is set to false:
- when the user increments the first month, it would be great to have the second month automatically following up, in other words enforcing that the first month is always chronologically before the second.
- when the user decrements the first month, the second month cannot be set before the startDate month.

The following video shows the 2 scenarios.

https://user-images.githubusercontent.com/6019103/120505276-1ef0c000-c3c5-11eb-8458-1e5231084614.mov

**Comment by dangrossman** [comment]
Feel free to add that capability if you'd like

I made this in 2012, there is nobody implementing feature requests today
