### ISSUE TITLE
Unable to change the month and year of the "To" date to the past.

### ISSUE THREAD

**Issue by gooners006** [dangrossman/daterangepicker#2210]
In this case, my selected default date is somewhat in the last few months (i.e April-June 2021), for example the last 3 months. I want to select a difrerent range, for example an arbitrary range of date of the year 2008. When I select the year and month on the left calendar but not the actual date, I'm unable to select on the right calendar the past date compare to the default selected date range ( i.e April-June 2021). I'm able to do it when I actually select a date. Is there any way for me to do it without having to actually select the date? 

Thank you

![image](https://user-images.githubusercontent.com/37095499/125716113-a6e92f48-f910-473a-8f0a-9c5cc37c4071.png)

**Comment by dangrossman** [comment]
There's not a way
