### ISSUE TITLE
Get dates betweeen startDate and endDate, excluding invalidDates

### ISSUE THREAD

**Issue by kredodevnicolas** [dangrossman/daterangepicker#2215]
Is there any way I can get the dates between, and including, startDate and endDate but excluding invalidDates?

**Comment by dangrossman** [comment]
Run a loop from startDate to endDate. In the body of the loop, check if the current date is in your invalid date list. If not, add it to some array. That array is now your list of dates from startDate to endDate excluding invalid dates.

**Comment by kredodevnicolas** [comment]
Thank you so much! Got it!
