### ISSUE TITLE
Option to disable auto start of day / end of day logic when timePicker is false

### ISSUE THREAD

**Issue by massivespace** [dangrossman/daterangepicker#2223]
I have a situation where I want to add a Last 24 hour selection, but I do not want to allow the user to select a custom time range.  I set the Last 24 Hours item to:
                      'Last 24 Hours': [moment().subtract(1,'days'), moment()],
But I also have timePicker set to false.  When the "onCallback" fires, it is passing a start date of yesterday at 12 am and today at 11:59:59 pm, ignoring the start and end dates I put in above.  It would be nice to have an option to disable this feature that seems to be setting the start date to "startOfDay" and end date to "endOfDay" when timePicker is false.  Currently, I just have to enable the time selection and hope the user doesn't utilize this feature.

**Comment by dangrossman** [comment]
You have several options:

1. The clicked label is the 3rd parameter passed to your callback. Check if it is "last 24 hours" and respond appropriately in your application

2. Change the code to work the way you want it

This project is not actively developed.
